### ISSUE TITLE
Visit IDs that overlap with WFD and uDDF region

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/DC2_Repo#108]
We would like to have  two lists of visits from the Run 1.1 `minion_1016_desc_dithered_vn.db` #98 by  Monday Jan 22  6pm. 
- [ ] `AllVisitsWFD_vn.csv` which is a csv file which has the set of visits (`obsHIstID`) from the above database that overlap with the main survey region for Run 1.1. Requires #98 
- [ ] `AllVisitsuDDF_vn.csv` which is a csv file which has the set of visits (`obsHIstID`)from the above database that overlap with the uDDF region for Run 1.1.  Requires #96 #98 

If this is trivial because the dithers are small enough (eg. in uDDF and the field is in the center, that is fine, let it be a trivially composed list)

Why do we want this ? The visit lists needed for Run 1.1 must be subsets of these (default would be the first set of observations from this subset) . 

@humnaawan probably has code ready to trivially do this. (please say if there is a problem for example either required inputs missing or something else.)

**Comment by humnaawan** [comment]
@rbiswas4 I didnt follow the naming scheme above since it ignores some of the things that were important for me to track their production. So `AllVisitsWFD_vn.csv` would be `DC2VisitList_minion1016_v3_WFDvisits_nside512_WFDvisitsInWFD.csv`, and `AllVisitsuDDF_vn.csv` would be `DC2VisitList_minion1016_v3_WFDvisits_nside512_WFDvisitsInuDD.csv`. 

Hope this wont be a big problem.

**Comment by humnaawan** [comment]
Also, here are GIFs that illustrate the three files that are in the data folder:

![hids_0-100index_udd_test_nside512](https://user-images.githubusercontent.com/12702187/35362959-a5ab9292-0135-11e8-80b5-e74ef4a1e319.gif)

^(=> The uDDF dithers working.)

Theres are first 100 WFD visits:
![hids_0-100index_wfd_test_nside512](https://user-images.githubusercontent.com/12702187/35362960-a5b3c322-0135-11e8-93d8-2ed69774a3e9.gif)

These are first 100 WFD visits that are in the uDD footprint:

![hids_0-100index_wfdinudd_test_nside512](https://user-images.githubusercontent.com/12702187/35362961-a5bd7fb6-0135-11e8-95c6-5ceca0d2e78b.gif)

**Comment by drphilmarshall** [comment]
Looks good, @humnaawan ! Nice work :-) Check out that non-flat sky coverage :-) 

I notice you provide a "bird's eye view" of the focal plane moving around beneath the celestial sphere, which is why RA increases to the right. And personally I am glad to see that after 6 months of being spokesperson I can still compute WCS offsets correctly :-)  

Just a quick comment on the visualization: shouldn't the black dots mark the sensors that are actually going to be simulated, while the solid black circle marks the undithered FOV (which doesn't really matter to us)? I'd be inclined to make that switch, and also make the undithered circle gray, so as to de-emphasize it. What do you think?

**Comment by egawiser** [comment]
I think Humna's planning to make that switch, since I made the same suggestion when we met today...  hopefully not an example of the "fools rarely differ" part of the saying...  I didn't insist on switching to "astronomer's view" with RA increasing to the left, but we should probably use that convention moving forwards.

**Comment by jchiang87** [comment]
Could the coordinates also be converted to degrees, please?   as in Phil's Run1.1 Specifications document?

**Comment by humnaawan** [comment]
Apologies for the delay but here are the updated GIFs with the requested changes:

First 100 DD visits that are in uDDF footprint:
![hids_0-100index_udd_test_nside512](https://user-images.githubusercontent.com/12702187/35837200-4e8e9b9a-0a99-11e8-892f-d66316dc80e1.gif)

First 100 WFD visits in the WFD footprint:
![hids_0-100index_wfd_test_nside512](https://user-images.githubusercontent.com/12702187/35837204-56ce8748-0a99-11e8-91ed-7f61f0571cbc.gif)

And finally, the first 100 WFD visits that are in the uDD footprint:
![hids_0-100index_wfdinudd_test_nside512](https://user-images.githubusercontent.com/12702187/35837206-5dbad160-0a99-11e8-8a30-cad8abbafc3e.gif)

@drphilmarshall @egawiser @jchiang87 please let me know if I'm missing anything!

**Comment by drphilmarshall** [comment]
Sweet! Thanks Humna, these look good to me :-)

**Comment by rbiswas4** [comment]
The requests for format of the visits files changed to a file for each band in uDDF and Main survey and this was completed.
