### ISSUE TITLE
Run 1.1 Visit List

### ISSUE THREAD

**Issue by humnaawan** [LSSTDESC/DC2_Repo#131]
@rbiswas4 looking over the [notebook](https://github.com/LSSTDESC/DC2_Repo/blob/master/Notebooks/SurveyDesign/get_visit_lists.ipynb) that produces the final list for the visits, it appears that we are not using the correct WFD visits: `DC2VisitList_minion1016_v3_WFDvisits_nside512_WFDvisitsInuDD.csv` has WFD visits that overlap with the uDD region .. not what we want for Run 1.1 which needs `DC2VisitList_minion1016_v3_WFDvisits_nside512_WFDvisitsInWFD.csv`.

I'm sorry I didnt catch this earlier but I misread Issue #98 ("Visit IDs that overlap with WFD and uDDF region") to mean visits that overlap both WFD and uDDF and thought the `WFDvisitsInuDD.csv` file use was intentional. We dont really even need that file, do we?

**Comment by rbiswas4** [comment]
@humnaawan As we discussed, that was a good catch! We will fix this and we have some time to get this done. As you point out the `DC2VisitList_minion1016_v3_WFDvisits_nside512_WFDvisitsInuDD.cs` is not really required.

If we learn our lessons, we should make this a test so that we don't repeat this mistake. I will add that as an issue.

**Comment by katrinheitmann** [comment]
@rbiswas4 Time is running out :-) When do you think this will be fixed? Tom will be back soon and we need to start Run 1.1 asap. Thanks!

**Comment by rbiswas4** [comment]
@katrinheitmann @humnaawan : Yes. The work is hopefully done in #132 .
