### ISSUE TITLE
Galaxy Ids length

### ISSUE THREAD

**Issue by jbkalmbach** [LSSTDESC/DC2_Repo#147]
While preparing the sprinkler for Run 1.2p I noticed that the new protoDC2-v3 galaxy ids are much longer than the v2 ids and this is causing issues for the sprinkler due to the fact that we multiply them by 10^4 to get the lens system information into the id. I think for Run 1.2p we can work around this due to its smaller size, but can we shorten them in the final galaxy catalog for Run 2.0?

**Comment by danielsf** [comment]
There is also an additional factor of 10^3 that CatSim multiplies the `galaxy_id`'s by to arrange it so that galaxy bulges and disks have separate uniqueIds.  This means that `galaxy_id*10**8` needs to be able to fit into a 64 bit integer without overflow.  Bryce found one case of `galaxy_id=355000000766271 ~ 3.6*10**14`, which will not fit.

**Comment by evevkovacs** [comment]
Dan should chime in, but what appears to have happened is that the simulation timestep is now included in the galaxyID. I am assuming this was done to ensure uniqueness of galaxy ids across the catalog. There are  10**7 galaxies in protoDC2. For cosmoDC2 this number will be multiplied by 200 (area factor = 5000 sq. deg/25 sq. deg) x 7 (volume factor = V(z~3)/V(z~1)). So expect ~2e10 galaxies, which gives plenty of margin for subsequent multiplications required.   cosmoDC2 will be split by healpixels, so we will be using that as part of the galaxyID, but will make sure that there aren't too many zeros padding the less significant digits.

**Comment by dkorytov** [comment]
The ID scheme encoded the time step into the ID. It was made to help in an internal step of going from snapshots to a light cone. Since it was unique IDs for the light cone, it was convenient to use as the galaxy ID. The GCR is now fixed to generate a new unique set of IDs for the galaxies. The IDs are now maximally compact going from 0 to (num_galaxies - 1). 

For CosmoDC2, we might have to have some sort of encoding scheme for the healpix pixels as Eve mentioned. 

Could CatSim multiply by +1 or -1 for disk and bulge ids respectively? Or multiply by 2 and multiply by 2 +1 for disk and bulge ids? That might be more robust against large ID values.

**Comment by danielsf** [comment]
The CatSim system is designed for a problem more general than separating out bulges and disks.  CatSim connects to several sources of objects (galaxies, supernovae, stars, asteroids...).  Each source catalog has its own internally unique numbering system.  In order to create a numbering system that is unique across all of CatSim, we take the (internally) unique ID from the source catalog, multiply by 1024, and then add an offset that is characteristic of that source catalog (for instance, bulge_offset=1, disk_offset=2, agn_offset=3, star_offset=4, asteroid_offset=5...).  Obviously, we may have gotten a little over-eager multiplying by 1024 (though we are up to several tens of individual source catalogs we can connect to).

All of which is to say: multiplying by -1 or by 2 won't be enough for our needs.  This system is pretty historical, so I am hesitant to change it now.  There is a lot of code that assumes it works the way I described.

**Comment by dkorytov** [comment]
Okay, that makes sense. I didn't appreciate that CatSim needs the diversity of internal tags. Thanks for clarifying! :)
