### ISSUE TITLE
Mismatch between the phosim images footprint and the reference catalog

### ISSUE THREAD

**Issue by boutigny** [LSSTDESC/DC2_Repo#159]
There is a mismatch between the area covered by the simulated images and the footprint of the reference catalog. The reference catalog is a little bit smaller and this is causing problem for the astrometry when there are not enough objects left for the fit to converge.
This is illustrated in the attached image where the circles represent the position of the references overlaid on top of an Eimage (raw). We see that there are reference objects only in the upper right part of the image.
Regarding the shift between references and simulated objects Scott told me that it is due to the lack of a proper model for the Earth motion in phosim. This is ok as long as the shift is small enough to be compensated by the matching algorithm.

Sensor with bad astrometry can be simply ignored when the astrometry fails with a Fatal error, but there can be cases where the astrometry is failing silently, so it would be preferable to have an exact match between the images and the reference footprint.

![download](https://user-images.githubusercontent.com/5713323/39525699-0354d866-4e1d-11e8-9ed1-60221277bd48.png)

**Comment by nicolaschotard** [comment]
I can add that this error only appeared for one sensor over the ~40,000 sensors I've processed. So the discrepancy between the reference catalog and the visits must be really small.

**Comment by boutigny** [comment]
but keep in mind that there could be some silent failures.

**Comment by egawiser** [comment]
Does the reference catalog cover just the DC2 area, or a slightly larger piece of sky?  I ask because we have a criterion that sensors should be simulated if there are at least 100 sources within the DC2 area that fall within them, so this issue illustrates that we need to combine that criterion with making our reference catalog cover the DC2 area expanded by the width of a sensor.

**Comment by boutigny** [comment]
From what I have understood he problem is also that we are superimposing several catalogs depending on the object types. I guess that the objects in the images above without references are "sprinkled" ones which are not added to the reference.

**Comment by wmwv** [comment]
The sprinkled objects are a small fraction of the catalog.

**Comment by egawiser** [comment]
@danielsf that's an important failure mode to avoid, but it would seem likely to lead to simulating a lot of sensors that have zero galaxies, and I haven't heard reports of that problem occurring.  It is my understanding that we trim the instance catalog to restrict objects to fall within the DC2 region, which should avoid the problem you mentioned.  When we do that, we're supposed to use an "adaptive radius" that includes stars outside DC2 if they fall close enough that their light should still be simulated; the formula for that was recommended by @johnrpeterson .

**Comment by jchiang87** [comment]
In the phosim pipeline, because we have "deconstructed" the phosim.py script in order to run in the SLAC workflow engine at NERSC, we're applying `minsource=100` somewhat differently.  This is by necessity for exactly the reason Scott mentions:  there will be stars from CatSim outside of the protoDC2 region.  To address this, we are applying the `minsource` criterion only to the galaxies in the instance catalogs.  

I think the reference catalog issue can best be handled simply by using a radius for the catalog region that covers, as you recommend Eric, at least a sensor's corner-to-corner distance outside of the protoDC2 region.

**Comment by danielsf** [comment]
Okay.  I will rerun the reference catalog script with a larger field of view

**Comment by danielsf** [comment]
The current catalog was generated with field of view = 3.6 degrees; I will increase that to 4 degrees, to be safe

**Comment by danielsf** [comment]
@boutigny Try
`/global/projecta/projectdirs/lsst/groups/SSim/DC2/reference_catalogs/dc2_reference_catalog_dc2v3_fov4.txt`

**Comment by katrinheitmann** [comment]
@danielsf @boutigny Was this resolved? Thanks!

**Comment by boutigny** [comment]
Yes it is resolved. I close the issue
