### ISSUE TITLE
Run protoDC2/CatSim catalog through PhoSim

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#17]
The CatSim output now needs to go through PhoSim to generate the image catalog.

**Comment by danielsf** [comment]
Except for one more lingering question about the meaning of the major and minor axes in the protoDC2 catalog (are they "projected on the sky" or some True three-dimensional quantities), this script

https://github.com/LSSTDESC/gcr-catalogs/blob/master/examples/phosim_descqa.py

does everything you need to produce PhoSim InstanceCatalogs from protoDC2.  I have generated a small catalog and successfully run it through PhoSim.

Is having this example script good enough?

What sort of API do we need?

Who is actually going to be doing the work of generating the images we want for the December sprint week?

**Comment by rmandelb** [comment]
> major and minor axes in the protoDC2 catalog (are they "projected on the sky" or some True 
> three-dimensional quantities)

Two numbers are insufficient to specify the 3D size of an ellipsoid (you would need minor, intermediate, and major axes, not just minor and major).  So I think these must be projected.

**Comment by danielsf** [comment]
Dan Korytov has clarified that inclination is already included in the major/minor axis columns.

That just leaves my other two questions, which really can be summarized in the third: who is going to be generating these images (so that I can talk to that person about how they want the interface to work).

**Comment by katrinheitmann** [comment]
Thanks Scott!! @johnrpeterson suggested that Glenn has time to run it through PhoSim and he is set up to do that at NERSC. John, can you confirm that Glenn is available? Then Glenn and Scott can talk about the interface question. @salmanhabib We should also set it up at Argonne, can you push that forward with John, Glenn, Tom U. etc?

**Comment by jchiang87** [comment]
@danielsf It looks like your `phosim_descqa.py` script only generates objects from the protoDC2 catalog, i.e., does not produce entries for stars, correct?  Also it uses the opsim db file from DC1, i.e., `minion_1016_sqlite_new_dithers.db`.  Is that what we want to use for protoDC2?   I think there are some things to sort out before we hand off things to the people running phosim.

**Comment by danielsf** [comment]
@jchiang87 Yes.  That script was only concerned with getting the protoDC2 objects into the catalogs.

Are we just going to use the catalog-generation infrastructure we used for DC1 (in which case, we can just include the DC2-specific classes defined here to replace the galaxy catalog classes), or are we starting from scratch?

**Comment by jchiang87** [comment]
I think we are basically starting from scratch, but I can help put together a complete script based on the DC1 stuff.  Assuming we just need to add stars (what about galaxies with AGNs?), then I think the main unsettled question is the opsim db file to use.   I don't see any reason not to use the one from DC1 if that's what's available now.

**Comment by danielsf** [comment]
Whether or not we add AGN depends on whether there are AGN associated with the galaxies in protoDC2.  @evevkovacs ?

minion1016 is still the baseline OpSim run.  The example script I linked to above is flexible enough to use any OpSim database (though there might be some breaking changes in OpSim v4; I know they changed the schema of the Summary table).

The example script does not do dithering.

**Comment by jchiang87** [comment]
ok so we would use the dithering code from the DC1 instcat generation script.

**Comment by cwwalter** [comment]
I think if you use the old DC1 OpSim database you can use the extra dither columns as added by the afterburner right?

**Comment by jchiang87** [comment]
yes, that's right

**Comment by evevkovacs** [comment]
@jchiang87 @danielsf  Yes, protoDC2 does have some AGN properties. 
blackHoleAccretionRate
blackHoleMass
are available

**Comment by danielsf** [comment]
Are we trying to do time domain science with DC2?  It's going to take more thought to figure out how to incorporate AGN variability into a new catalog.  I am almost out of time I can devote to this (I need to deliver some new simulations to the project in the next few weeks).  I can provide some coaching for someone trying to implement AGN variability in this catalog, but I'm not sure I can actually be the one to do it.

**Comment by jchiang87** [comment]
I think for protoDC2, AGN variability isn't needed, but someone should correct me if it is.  For DC2 itself, we definitely want to do time domain science, e.g., SNe and strongly lensed AGNs, but I think the DC2 data production won't occur until late February at the earliest.

I can put together the full script to generate the protoDC2 instance catalogs, though I'm wondering if it would be desirable to move the non-importable code to a `if __name__ == '__main__'` section in your `phosim_descqa.py` script and add an `__all__==[...]` so I can import it into a final instance catalog generation script.   Otherwise, I can just update that script to include the stars, etc..

**Comment by danielsf** [comment]
Yeah.  That script needs to be refactored.  I expected there to be a longer review before anyone pushed the Big Green (merge) button.  I will do a quick refactor and issue a new pull request to gcr-catalogs.

Thanks, Jim.

**Comment by yymao** [comment]
@danielsf I thought `phosim_descqa.py` is just an example script? If you refactor the code to make it importable lib, maybe also move it out of `examples`?

**Comment by danielsf** [comment]
@yymao I am about to issue a pull request so that you can see what I mean.  See you in gcr-catalogs...

**Comment by danielsf** [comment]
New hurdle.  GCRCatalogs appears to be broken
https://github.com/LSSTDESC/gcr-catalogs/issues/20

**Comment by danielsf** [comment]
PR issued

**Comment by yymao** [comment]
For those who want to track our progress see https://github.com/LSSTDESC/gcr-catalogs/pull/21

**Comment by jchiang87** [comment]
With Scott's help, I added a `generateDc2InstCat.py` script that creates instance catalogs with DESCQA inputs and stars ( #44 ).    I see that LSSTDESC/gcr-catalogs#21 has been merged, so I think the `generateDc2InstCat.py` script is ready to be exercised at NERSC.  I'll try to find time later today, but if someone else wants to give it a whirl, please go ahead.

**Comment by cwwalter** [comment]
>  The region of the sky covered by protoDC2 appears to be centered on RA, Dec = 0, 0.

I thought the idea was to use a subset of DC1 for the sprint week so you could get the extra dithering column?

**Comment by jchiang87** [comment]
If I use one of the visits from DC1, I get no galaxies from protoDC2.   I may be mistaken, but I think any visit in `minion_1016_sqlite_new_dithers.db` has that column.

**Comment by cwwalter** [comment]
Ah, OK I see.  Yes, I think that is correct as long as you are using the same sqlite file.  Were the protoDC2 galaxies already generated at a particular 25 sq degree position?

**Comment by katrinheitmann** [comment]
Here is an image of the sky area covered as a test in DESCQA: 
https://portal.nersc.gov/project/lsst/descqa/v2/www/?run=2017-11-15_17&test=SkyArea

**Comment by cwwalter** [comment]
Cool!  Is the DC1 image correct?  I remember it was chosen by @humnaawan and @egawiser for average density, dust etc and didn't think it was at 0,0.

**Comment by danielsf** [comment]
In the context of the link Katrin sent out, DC1 means "the galaxy catalog on fatboy."  I believe they are just running the 4.5 by 4.5 degree tile that we use to generate the full-sky fatboy catalogs through the DESCQA validation tests.  That 4.5 by 4.5 degree tile is centered on RA=0, Dec=0.

**Comment by cwwalter** [comment]
> In the context of the link Katrin sent out, DC1 means "the galaxy catalog on fatboy." I believe they are just running the 4.5 by 4.5 degree tile that we use to generate the full-sky fatboy catalogs through the DESCQA validation tests. That 4.5 by 4.5 degree tile is centered on RA=0, Dec=0.

OK got it.  Thanks.

**Comment by jchiang87** [comment]
Here's a plot of the pointing directions of the dithered visits in `minion_1016_sqlite_new_dithers.db` that nominally overlap with the 5x5 protoDC2 region.   The grey region is the footprint of the instance catalog of galaxies obtained using the `generateDc2InstCat.py`script for visit `138143`, assuming a fov ~2.0 deg radius. 
![protodc2_visits](https://user-images.githubusercontent.com/1994473/32922821-00c3653e-cae9-11e7-9fff-c2ab45926467.png)
So we would need to run phosim for ~8k visits to get full depth coverage over the protoDC2 region (there are a relative handful of visits in the corners that don't overlap with the protoDC2 region).  Of course,  this wouldn't mean ~1.5M sensor visits (=189*8000).  Assuming the sensors outside the protoDC2 region get trimmed, I guesstimate it will be around ~0.4M sensor visits.

**Comment by jchiang87** [comment]
The `generateDc2InstCat.py` script is finally done and the code has been merged into master via #45.

At NERSC, I've installed the code in `/global/cscratch1/sd/jchiang8/protoDC2` and put a README with instructions in that directory.  The time-ordered list of visits are in the `protoDC2_visits_*-band.fits` files in the [scripts/protoDC2](scripts/protoDC2) folder.  Since the instance catalogs take up a lot of space, I'd generate them on a per visit basis, then delete them once phosim has been run for that visit.  Note that in order for proper motion to be disabled, the `--disable_proper_motion` option has to be given on the command line.

**Comment by egawiser** [comment]
@jchiang87 we discussed this with @johnrpeterson and @cwwalter on another issue somewhere, but it appears that the following approach would enable (proto)DC2 to include realistic scattered light from outlying bright stars without causing CCDs outside the desired 5x5 degree area to be simulated:  
-remove galaxies and dim stars (say r>10) that lie outside that region from the instance catalogs
-set PhoSim to only simulate sensors that have a minimum of ~100 objects on them (might have to tune that threshold)

**Comment by johnrpeterson** [comment]
Eric, one issue related to this is that there will be some non-negligible computational cost to including these brighter stars.  (Ironically, when you speed up background everything else becomes significant)  The bugs related to very long run times with bright stars are gone.  But there is still some cost to these bright stars because if you include ghosts (which is why you like them), then just the stars in the 6-10 mag range may add some real amount to the total CPU cost (~10% to 30%?).  (They do run faster if you turn off ghosts, but then you don't care about them).  I don't think there will be hardly any cost to the 9th mag stars.   But 6-9 is probably non-negligible.  So its up to y'all whether you think the cost justifies these.

**Comment by katrinheitmann** [comment]
Since we started Run 1.0 yesterday, I suppose this issue can be closed for now.
