### ISSUE TITLE
Tutorial notebook(s) for coadd catalog

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/DC2_Repo#185]
We already have [one notebook](https://github.com/LSSTDESC/DC2_Repo/blob/master/Notebooks/DC2%20Coadd%20Run1.1p%20GCR%20access%20--%20HSC%20selection.ipynb) that @EiffL has contributed. @fjaviersanchez also made [a testing notebook](https://gist.github.com/fjaviersanchez/8045435cc4e08c9a5ba2cf2e5b55b138).

And @EiffL and @fjaviersanchez are further developing the ideas for the coadd catalog tutorials [here](https://docs.google.com/document/d/1B_tx8_DLqmI12ouL5nsV1pKFLo-YYaSDar219YXmSSQ/edit).

**Comment by EiffL** [comment]
We have merged our tutorials. Parts I and II are ready, and I'll make a PR to add them to them the README. 
[Part III](https://github.com/LSSTDESC/DC2_Repo/blob/master/Notebooks/DC2%20Coadd%20Run1.1p%20GCR%20tutorial%20--%20Part%20III:%20Guided%20Challenges.ipynb) was meant to be a guided tutorial, with cells that people have to fill-in themselves,  we still have to agree on how to do this correctly. For now, the code is in the cells, but we would want to hide it somewhere. Suggestions welcome @drphilmarshall @wmwv  Otherwise, we can turn it into a regular notebook.

**Comment by yymao** [comment]
These notebooks are all in place now :tada:
