### ISSUE TITLE
Evaluate whether we need to update dust maps and tools for DC2 with the LSS, PC, and PZ groups

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#23]
Dear LSS, PC, and PZ groups,  

( @erykoff @nregnault @slosar @damonge @sschmidt23 @morriscb could you please point this issue out to the relevant people who can answer if that person isn't you?)

We are making our way through the DC2 wishlists everyone presented at Stony Brook and there were a few things we needed some clarification on.  Could you help us with them?  Specifically, there were requests for new more realistic dust maps and tools to use them. Currently we are using the SFD integrated dust maps.   We were wondering:

- Do the  photo-z and LSS group feel we need to update from the SFD integrated dust maps to Schlafly or something else?

- Do you need less than <1 arcmin resolution in the integrated dust map?

- Currently, each of line of site is assumed to be distributed with a smoothly varying analytic function.  We are wondering if this is OK for the PC group?  Are you planning on trying to use stellar photometry to map out the dust?

- The LSS group asked to to be able to "Query Dust Maps".  The catalog will already have extincted and unextincted magnitudes.  Is this enough or do you need another external tool that will allow you to query the map?

Thanks!

-Chris

**Comment by slosar** [comment]
Hi,

I think SFD is fine from now, but I think it's resolution is below the true variations in the dust maps. I'm not an expert, but people in the CMB community should know a lot about the dust. For the time being, once you get a more realistic dust post spectrum, you can just add noise to the SFD dust map (but note that noise needs to be non-white, because dust *does* have a correlation length). Extincted and unexctincted magnitudes are fine, but we need both the actual true magnitude and the pipeline unexticted magnitued, which will be noisy wrt to the truth.

**Comment by sschmidt23** [comment]
Similar to what Anze said, I think the PZ concerns were with systematics that might be induced if the assumed dust map was incorrect (e.g. spatially varying R_V that is not accounted for) and/or of finite resolution.  If a slightly incorrect dust map was part of DC2, then having truth, extincted, and unextincted (with slightly incorrect map) was along the lines of what we were thinking.  Is the PC group doing any work on the potential systematics induced by an incorrect dust map?

Also, note that at least for PZ, we could do these tests independent of DC2, making our own fake dust maps and testing impacts on photo-z stats, so it would not be a huge problem if DC2 used SFD.

**Comment by cwwalter** [comment]
> Extincted and unexctincted magnitudes are fine, but we need both the actual true magnitude and the pipeline unexticted magnitued, which will be noisy wrt to the truth.

Does the pipeline try to calculate this using the dust map, or just report magnitude at the top of the atmosphere?

**Comment by cwwalter** [comment]
@erykoff @nregnault Do you have any comment on this issue from the PC perspective?

**Comment by erykoff** [comment]
Dealing with questions of the reddening is definitely something that is on the PC roadmap, but not something that we have directly tackled so far.  I think it naturally fits within PC because it is very cross-cutting in DESC, and outside the purview of LSST DM.  

That said, I agree with @sschmidt23 in that a lot of these problems are best investigated outside of the full DC2 sims, as questions of the impact of incorrect extinction on photo-zs (and clusters) do not require pixel-level image sims.  Adding a small amount of error between the "true" dust map used in the sims (with appropriate noise spectrum) and the "apparent" dust map used to perform reddening corrections is not crazy, but since the problems caused by the dust maps are somewhat orthogonal to the problems probed by image simulations (in particular, the dust map is fixed for each position/object, so there aren't any multi-epoch variables at play here), making multiple fake dust maps would be both easier and more effective.

Finally, answering @cwwalter 's question.  As far as I know, the DM pipeline produces "top-of-the-atmosphere" fluxes, and it is DESC responsibility to get from there to the "top-of-the-Galaxy".

**Comment by slosar** [comment]
"top-of-the-Galaxy" :) one should put this in a paper some day... haha

**Comment by cwwalter** [comment]
OK so just wrapping this up.  Everyone things that the current SFD map we are using now is OK for DC2 correct?

One thing that wasn't addressed:

> The LSS group asked to to be able to "Query Dust Maps". The catalog will already have extincted and unextincted magnitudes. Is this enough or do you need another external tool that will allow you to query the map?

@slosar and @damonge could you comment on this?

**Comment by fjaviersanchez** [comment]
I think that is just to query the SFD map but @slosar and @damonge should comment on this

**Comment by slosar** [comment]
Well, in principle eli+dm will process dm outputs so that there will be a queryable map, but I don't think this is DC2's part -- this is general infrastructure.

**Comment by cwwalter** [comment]
OK thanks all. Closing this.
