### ISSUE TITLE
Utilize multiple galaxy inpainting methods

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2_Repo#25]
@slosar suggests to use not only Galacticus but a second approach to inpaint galaxies, or turn the knobs on Galacticus to see what is the effect. Any comments/thoughts on this @katrinheitmann @evevkovacs?

**Comment by yymao** [comment]
I think that's a good idea. While we have Buzzard (which is using a different galaxy-halo connection), it would be nice to have different galaxy-halo connections on the same halo catalog/trees. In addition to tuning Galacticus parameters, we can also run some empirical models on the halo catalog/trees once they are available.

**Comment by fjaviersanchez** [comment]
@yymao How feasible (in terms of CPU hours/storage/people working) would this be for DC2?

**Comment by yymao** [comment]
@fjaviersanchez My impression (but @evevkovacs should chime in) is that it is not feasible to run multiple Galacticus models for the full DC2 volume. For proto-DC2 it is doable, but would still take some considerable amount of time. Empirical models or galaxy mapping method (like the method used by Buzzard) are much cheaper and should be no problem to run on DC2 volume. However, these models may not produce all the features Galacticus provides, so it would be good to know a bit more about the use case.

**Comment by fjaviersanchez** [comment]
Thanks! I think that @slosar should tell us more about the use case that he has in mind then or if it would be enough to test in a smaller volume.

**Comment by salmanhabib** [comment]
It is feasible to run multiple Galacticus models for larger volumes using MC sampling based on a set of a smaller runs. We are working on this at Argonne (work led by Andrew Hearin).

**Comment by salmanhabib** [comment]
We can also implement hybrid models that combine SAMs and empirical approaches.

**Comment by yymao** [comment]
@fjaviersanchez @slosar I should also clarify that both @salmanhabib and I are talking about catalog level  (i.e., before SSim). Image generation for full DC2 is also very expensive and as far as I am aware, we are planning on putting only one catalog into the image generation pipeline.

**Comment by salmanhabib** [comment]
Just to confirm what @yymao just said -- the image generation, whether through PhoSim or GalSim is very expensive, most likely we will only get one image catalog of the full area, but we may be able to get multiple snapshots of smaller areas.

**Comment by slosar** [comment]
This is all fine. The logic is to test one thing at a time. We use images to test what garbage does catalog->images->catalog does and we use two (or more) different inpainting methods to test that our biasing/non-linear model is sufficiently general and to which scales it works.

**Comment by katrinheitmann** [comment]
Yes, there will be more options -- we are working on gaussian resampling 
method that will allow us to use different approaches (see planning 
document). The on caveat is that running phosim/imsim on top of the 
extragalactic catalog is expensive -- so I am not sure how many 
end-to-end simulations (from extracalagtic catalog to image catalog to 
DM catalog) we will run. In particular since LSS needs a big area. Did 
he mention at which stage he wants to see multiple catalogs?

**Comment by fjaviersanchez** [comment]
Ok, so my take from this is that multiple inpainting methods at the LSS catalog level seems feasible (for which volume is now the question) and it would be an interesting problem to check, and for the image simulation level we will just use the current Galacticus model. 

I would say that to study the non-linear behavior we don't need the whole volume (although it would be great if we have it).

Any other thoughts @slosar ?

**Comment by yymao** [comment]
@fjaviersanchez @slosar the other question is if there are particular aspects of the inpainting methods you want to vary for this test. Even with just Galacticus there are many parameters one can adjust, and one can also try completely different galaxy-halo connection models. Knowing the use cases can also help us find suitable variations to try.

**Comment by evevkovacs** [comment]
@slosar We have many choices available with the Monte Carlo resampling technique (galaxy properties could be obtained from a variety of sources besides Galacticus outputs). Which properties are the ones you care most about? Changing Galacticus parameters is trickier. We are working on prediction tools for the effects on various observables of changing parameters. The simulations for this are still ongoing.

**Comment by aphearin** [comment]
I agree that DC2 would benefit from models beyond Galacticus. My current plan is to use the (recently completed) [galsampler](https://github.com/aphearin/galsampler) code to scale up and transfer several existing SAMs into Outer Rim. 

This duty is simplified by a very recent public data release of three different SAMs built into MDPL2 - [this paper](https://arxiv.org/abs/1710.08150) releases Galacticus, SAGE, and SAG into the CosmoSim database. `Galsampler` can transfer each of these synthetic catalogs into Outer Rim, giving us three up-to-date SAMs. 

Additionally, the same exact methods will work for the EAGLE hydrodynamical simulation, whose data is also [publicly available](http://virgodb.dur.ac.uk:8080/Eagle/Help) in database form. This will give us a "state-of-the-art" hydro simulation grafted into Outer Rim for DC2. If anyone knows of other publicly available hydro simulation snapshots, we could use those as well. 

I think this will give us more than enough diversity for DC2, but probably @slosar and/or @fjaviersanchez should weigh in since they raised this concern.

**Comment by fjaviersanchez** [comment]
@aphearin This sounds great. My impression is that @slosar wants to test different non-linear/biasing models (please correct me if I am wrong) so, just having more than one code would probably be enough (and 3 will definitely be great). I think that these tests will be done in terms of 2-point statistics at small scales so, probably we won't need even a big volume for this (but the bigger the better, especially if we want to test LSST-like sensitivities). In any case, I think that what you are planning is more than enough for our goals.

I would say that we shouldn't go beyond that because I am worried that, even having an additional simulation or even more models, the human resources that we have are limited so, at the end of the day these additional things won't be analyzed or they'll be rushed. I think we shouldn't go overboard. 

Of course if any of you have a different opinion feel free to correct me.

**Comment by slosar** [comment]
Yes, yes, let's not go crazy. I've already raised the issue of the need to have biasing model testing framework as a separate project with rachel. This should be done outside DC2 within TJP. I just expressed a wish for 2 models at the catalog level, so this is enough -- no need for 20. :)

**Comment by yymao** [comment]
For reference, in #20 we discussed testing galaxy bias model in DC2.

**Comment by katrinheitmann** [comment]
Andrew added Section 4.2.2 to the planning document that describes the GalSampler approach that will address the discussions above. For now, I think we can therefore close this issue since it is captured now sufficiently. I guess at some point we will have a new issue actually testing on different catalogs but that is probably more an issue for LSS rather than DC2.
