### ISSUE TITLE
Make accessible snapshot data for a few snapshots?

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2_Repo#27]
I think that the CL group wanted this and @katrinheitmann @evevkovacs said that it was feasible. Do I recall this correctly? How many snapshots would be interesting for CL @erozo @anjavdl?

**Comment by yymao** [comment]
BTW, snapshot data have also been requested in #7 and #20. We do have the infrastructure to supply snapshot data. Knowing the redshifts needed would be good.

**Comment by erozo** [comment]
I expect at least two, one "low" redshift (z~0.2) and one "high" redshift (z~0.9).  Exact values not important.  If there was need for more afterwards, we can ask then.  @anjavdl you agree? Anything to add?

**Comment by evevkovacs** [comment]
@erozo @anjavdl  What properties do you need in these catalogs? We currently have the usual galaxy properties, plus halo id, FOF halo mass, position and velocity. In your wish list you mention SO masses and projected masses. We can provide SO masses which are computed on the potential center of FOF halos. Could you clarify what you mean by "projected masses"? Is this a requirement on the DC2 catalogs used to make images?

**Comment by evevkovacs** [comment]
@erozo @anjavdl You also listed lensed input catalog and halo catalog. Please explain.

**Comment by erozo** [comment]
All galaxies are lensed: their apparent position is not their true position.  If the halo catalog is recorded in terms of their true position, but the galaxies are lensed, then the location of halos won't match the location of clusters.  To evaluate cluster finding, we need to know the apparent position of the halos, hence lensed halo catalog.  Does that make sense?

**Comment by erozo** [comment]
Re halo catalogs.  Can we run with SO finders instead?  FOF halos is not something that we can replicate observationally (even roughly), so it's much less useful than SO halo catalogs.  Likewise, halos typically have a central dominant substructure which will host a massive galaxy which serves as a flag post for centering clusters, so centering on substructures is desirable for optical cluster finding; some average FOF position will adversely affect our analysis in ways that are not really inherent to the data, but rather stem from the choice to use FOF rather than SO halo finding.  If it's too late to change things, it's too late, but SO halo finders are clearly much, much preferred on our end relative to FOF halo finders.  FOF masses are also problematic numerically (1103.0005).

**Comment by erozo** [comment]
I think the "projected masses" refers to having the ability to compute \Delta\Sigma profiles directly so that they can be compared to the lensing outputs.

**Comment by erozo** [comment]
@anjavdl Feel free to contradict me (or support me) on any of the above points. :)

**Comment by salmanhabib** [comment]
@erozo, Yes, we have SO properties as well of course -- you can pick your poison. We don't use an FOF center (however defined, as max density point or otherwise), we use the potential center. This is always centered on the largest mass concentration. So, don't worry, it's all standard.

**Comment by anjavdl** [comment]
Looks like @erozo cleared up all the questions.  :-)

Re. the projected masses - since the DC2 image simulation will be comparatively small for clusters purposes, we will still need to rely on catalog / snapshot outputs from large-volume simulations to calibrate our lensing mass measurements.  I.e. we will need mass projections (within long cylinders) and derived products (shear and magnification maps) of the halos returned by the halo finder. 

Having these projections for the same halos as in the DC2 image simulation will be a valuable cross-check.

**Comment by katrinheitmann** [comment]
@anjavdl @erozo I want to close this issue and make sure we have captured what is needed in the planning document. If you have a much larger area (3k-5k) just from the extragalactic catalogs, do you still need snapshot outputs? Can you explain why and what you would need in those? We can provide them but I want to make sure they are really needed. With the IA folks we now decided that they actually only need snapshots for the small test case but not for the full DC2. Thanks!

**Comment by erozo** [comment]
I believe the main motivation was verifying mass calibration.  If ray tracing is sufficient to be limited by the simulation resolution, and we have the lensed halo positions, we may be okay without the snapshots.  What do you think @anjavdl ?

**Comment by katrinheitmann** [comment]
I am going to close this right now. I think if for DC2 we deliver the 5000 sq degree of extragalactic catalog, that should be sufficient. If you really desperately need the snapshots we can come back to it. I personally think it is easier to manage the data products if we stick to a smaller set.
