### ISSUE TITLE
Validation tests for protoDC2

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#30]

**Comment by yymao** [comment]
- [ ] dN/dmag
- [ ] shear sign convention

**Comment by evevkovacs** [comment]
- N(z)

**Comment by yymao** [comment]
- [ ] Equivalent Width distributions in H alpha and [O III] at z<1 (see #31)

**Comment by yymao** [comment]
For each validation test I created an issue in https://github.com/LSSTDESC/descqa/issues so that we can keep track of individual progress without spamming this repo.

**Comment by rmandelb** [comment]
Apologies if I am missing something - I am traveling back home today and my ability to keep up with e-mail and slack etc. is not all there.  There's an epic here and there's an epic in the descqa repo with a similar name.  What is their relationship / how do you envision they will be used?

**Comment by katrinheitmann** [comment]
Sorry, I am trying to clean this up --

The #30 was introduced a while ago following the idea that we need to 
track what is now table 7 in planning document. With that epic, a few 
validation tests were introduced in the DC2_repo. Yao decided that it's 
better to have the tests in descqa instead of DC2_repo, so the issues 
got duplicated.

Since Yao is doing a great job in managing the validation issues, I want 
to close the issues in the DC2_repo. But at the same time, the DC2_repo 
will still be used for tracking and the progress_repo. So I do need the 
connection to the descqa repo.

The connection is now the two epics. The DC2_repo is basically now only 
there for allowing the track the descqa repo epic. So we will keep both 
epics but only the descqa repo will be meaningful.

If I understood all instructions from Phil/Anders correctly, this will 
hopefully work ... ;-)

If not, I have to do something different.

But short summary: yes, I am aware of the two epics and trying to make 
sure they are not confusing.

**Comment by awborgland** [comment]
Looks good. It still contains two DC2_Repo issues (in addition to the descqa issues). Are you planning to keep them? I don't mind - just curious.

**Comment by katrinheitmann** [comment]
not done yet -- get interrupted here all the time. :-) And already got 
an email from Rachel about "what's going on with those epics" ... Better 
to do this late at night when nobody is watching ;-)

I wanted to close the two issues and just make a note that they are in 
the descqa issue now. Give me a couple of minutes ...

**Comment by awborgland** [comment]
@katrinheitmann , I think I was multitasking with one too many tasks yesterday. Why didn't you just include the descqa Epic itself, instead of all the issues individually? That way you will automatically 'include' any new issues that are attached to the descqa epic. When you include an epic, you get an option of displaying all the issues in that epic so you will still be able to see all the underlying issues.

**Comment by katrinheitmann** [comment]
I actually added the issues to the DESCQA epic -- I thought the idea is 
to have issues underneath an epic? Then the DC2_repo epic just 
automatically picked them up (in other words, I did not in fact added 
the issues to the DC2_repo epic). Maybe what you are not "happy" with is 
that in the descqa repo I added each issue to two epics now ...? I am 
happy to undo that if that will still give us the burn-down chart in the 
DC2_repo. I'll look into it later ...

**Comment by awborgland** [comment]
What I had in mind is 

1/ Add descqa issues to descqa epic
2/ Add descqa epic (only) to corresponding DC2 epic 

The advantage with that is that as more descqa issues are added to the descqa epic, the DC2 epic will automatically pick them up through the descqa epic (and people will only have to remember to assign an issue to one epic, not two, especially since assigning a descqa issue to the DC2 epic means using ZenHub to connect the two repos).  This would minimize the chance of the two epics being out of synch and should be completely equivalent to assigning each issue to both epics including, I think, being able to use the burndown chart in DC2 on the descqa epic, but you're right that you should verify that. What a convoluted sentence. I need a second double espresso.

**Comment by katrinheitmann** [comment]
I am closing this issue -- all the work has gone over into the descqa repo and not much is being updated here so might as well close it. If anybody feels differently, feel free to reopen.
