### ISSUE TITLE
Technical WGs' DC2 analysis projects?

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#37]
@antilogus Can you please head on over to the [DC2 planning document on overleaf](https://www.overleaf.com/read/jwbjvjnszkzf#/43020815/) and edit Section 2 with details of any technical WGs' planned uses of the DC data, please? @rmandelb has enumerated the analysis WG uses with either a 'C' or an 'I' according to whether the extragalactic catalog or the simulated images will be used. (This is a follow up to #36)

**Comment by drphilmarshall** [comment]
PS. @katrinheitmann can give you write access if you don't already have it...

**Comment by antilogus** [comment]
Ok , I can edit it , I'll do it Thursday ,

**Comment by drphilmarshall** [comment]
Thanks!

**Comment by antilogus** [comment]
- So SAWG has action associated to BF for DC2 (by the way as DC2 get closer , we got at last interaction between DC2 people and SAWG people to validate DC2 content / goal from sensor point of view ) , so I put 2 lines in the document.  
- The PCWG , said since the start that its contribution to the calibration is on the larger scale than what DC2 will cover  .... and anyway their R&D request real data ( They could validate if the  DC2 simulation is good from calibration / distortion perspective ... but for the moment there is no move in this direction , and it's not the scope of the text )

**Comment by katrinheitmann** [comment]
@drphilmarshall I suppose we can close this issue? Thanks Pierre for adding this to the document!

**Comment by drphilmarshall** [comment]
Yep - thanks @antilogus ! :-)
