### ISSUE TITLE
List of sensor effects and artifacts to include

### ISSUE THREAD

**Issue by drphilmarshall** [LSSTDESC/DC2_Repo#4]
@cwwalter @fjaviersanchez I heard you were going to assemble the complete list of sensor effects and artifacts, check which ones must be left out of the DC2 image simulations because DM cannot remove them yet, and then propose which of the others should be included. This is related to the question of whether we should make 2 15-s snaps for each visit, or just a single 30-s visit exposure. Will you make this list directly in the plan in overleaf?

**Comment by cwwalter** [comment]
Yes, we are :)

For DC2 I was planning on listing what we are actually including in the roadmap document as this should describe document what we actually are doing/did.

**Comment by cwwalter** [comment]
To start for reference here is what I think is a pretty complete list of effects.  Note: **this is NOT the list of effects to turn on/implement for DC2**.  It is a list of possible effects and implementation status.

- A/R Coating
- Fringing
- Charge Diffusion
- Debris on surfaces (-> non-uniform QE)
- Field-free non-uniform layer (-> short wavelength QE variations)
- Brighter-Fatter effect
- Tree Rings
- Edge effects
- Pixel boundary errors
- Dead Layer 
- Cross talk (infrastructure exists, but not sure if values validated )
- Midline Stop (for relevant sensors)
- Blooming 
- Pixel size variation 
- Bias
- gain
- Segmentation
- pre/over scans
- non-linearity (sensor)
- non-linearity (amplifiers)
- CTI
- hot pixels/columns
- ADC errors
- dark current
- read noise
- cosmic-rays 

I think PhoSim has already implemented all of this (except perhaps the midline stop). Items I think that are not currently in imSim development or production are:

- Cosmic-rays
- ADC errors
- hot pixels/columns
- Debris
- Midline stop / Blooming
- Pixel size variation

@jchiang87 points out that some of these things will also be handled by masking so those should probably be grouped together as we may want to handle them separately).  Please edit this comment to refine and correct it.

**Comment by cwwalter** [comment]
Knowing which things to turn on for DC2 involves both requests from the WGs and also consultation with the DM team.  Initial feedback suggests from the WGs suggests

BF, tree-rings and saturation, and perhaps fringing and cosmic rays.

**Comment by katrinheitmann** [comment]
Given that we want to start the phosim runs on the protoDC2 catalog soon, it would be good to converge on this so that the next PhoSim runs include what is needed as far as it is available. Also, Rachel brought this up before, how to we validate the effects, any suggestions? @cwwalter Do you think you can finalize this list for DC2 very soon or do we need to finalize the spreadsheet first? Thanks!

**Comment by cwwalter** [comment]
Hi Katrin,

Currently, this is one of the HWs we are working on.  I am talking to the WGs and also to SAWG and the project about some validation sensor issues.  We need to get this onto the spreadsheet when we know the answers.  Then,  we need to put our plans into the DC2 roadmap document and distribute it to the WGs so that they can comment and sign off on it. 

This is also true of many other things (cadence, dithering scheme, IA, etc etc etc).  

Is there something particular you want to test with protoDC2 at the imaging level right away?  We are doing phoSim timing tests (if that is the concern) separately.

**Comment by salmanhabib** [comment]
@cwwalter, who is doing the PhoSim timing tests?

**Comment by cwwalter** [comment]
Tom and Seth and all:

https://github.com/LSSTDESC/DC2_Repo/issues/19

For more discussion of the visits they will use etc.

**Comment by johnrpeterson** [comment]
Chris-

We started the timing tests a couple months ago here:

https://docs.google.com/document/d/1f5aoP9ND62NNwdfcex21zYcdnY3VFTZkLgRyYP4yPy8/edit

Salman is working on it too, BTW, and he already made an estimate for the charge CPU hours based on the results, which you can see in the summary.  Please add additional material there too, if we need to do any further testing.

John



On Oct 30, 2017, at 11:20 AM, Chris Walter <notifications@github.com<mailto:notifications@github.com>> wrote:


Tom and Seth and all:

#19<https://secure-web.cisco.com/1jMvrKRnfULBkCfxkxs8NGZZl8MNkBasa-k5HnpI9zNrhOpBuHTJY3STEG5jnfJAaa9SRfUj9bEKOtoTo5n2a4ywY7sHaycdSND8e3DN19lRUivKMpCorddWjb63Rbpp0x7D37gsnyO_fHeRJsTTC3DwKxDtnQBN3X990HG7nTeTDETjwgOu4wDTKBNAPjOWSEIDyGslHL-Ueq3PTiKd7y3yRrHhrIy6AVW7Y3BlC8vD2gMr-IGAGX45FcozX3NhPHhlzkCBFiwE_sXm51AYoJxxKloBKSap5B_VMEZKkKMbQz0VX_kiHYNgJ5g4BFwZAONDHR1ICukRFcPK0WEMgX7P4BK_sL-Wq3DeyK_hK8oQ/https%3A%2F%2Fgithub.com%2FLSSTDESC%2FDC2_Repo%2Fissues%2F19>

For more discussion of the visits they will use etc.

**Comment by cwwalter** [comment]
Hi John,

Thanks.  Yes, we know about this and Salman has reported on it to us.

We are trying to understand the relative scaling factors in the real environment we ran in before with a variety of realistic visits so we can tie the new numbers to the actual throughput.  We will make sure any results are also reported so they can be incorporated.

**Comment by johnrpeterson** [comment]
i’m not sure what you mean.  those numbers are realistic visits.  what are you testing or what do you mean by real environment?

On Oct 30, 2017, at 11:35 AM, Chris Walter <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi John,

Thanks. Yes, we know about this and Salman has reported on it to us.

We are trying to understand the relative scaling factors in the real environment we ran in before with a variety of realistic visits so we can tie the new numbers to the actual throughput. We will make sure any results are also reported so they can be incorporated.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1RXOg71oBekY8QCTfsi-FIkad8yxoxPukdDIrLgc-OgyGrR5CETEtpy6JcLooGEzXMhKEyFYNzUvQnB47ZhlnC6EUziN8ZOH8DfldHbfV0OJwjZxgMDLoSCui_reRUFfvTPVDpxZvskKbvDVhbKVNkyKqsv377V2Ya9YujpaJjAXkj2pQDMwlbQX3vogIynNL2crV1Dl8NfiZg95QsKqZuaKKntGKZM2Jy9kHmTYLajSMeH1tn_0eWAbZyHU_aERihqDd_aWMDYdcG3lipnwdEL7LSnBzE5BPxBFgYxYNjZBpoal6DDEMata24rabjzoB2lROIB3rAm6Zw5BhPwhT5fzFO8gUQAPOdJI1dqtBCjI/https%3A%2F%2Fgithub.com%2FLSSTDESC%2FDC2_Repo%2Fissues%2F4%23issuecomment-340482913>, or mute the thread<https://secure-web.cisco.com/13tMY6v4w9KaFBsZ0pJk-Ke1GczdpNUr5KYhnxWLE9NYNNNI_8G9UCsXt_sktiby1a-p_4G02OTL3lfWNfwpQVKMevwX-OtCr-q4eloprWicsyMTob-pDNzXRPtsXgsQQekJ3lDOhKjyaXooklR92g4N9UXF9MpIKQGFFVyoDGNLJ6i2ceM6g3trScmdoGPNCDSQPLTAzRlVE7vtNvxPpfSloya6otzpF1b4OA6XljMAnmXKO4dfLa9e4eSqi0Nueny3KohJpDzR-Z8UpsBRQ18cSxlLiMfyUj1sdLQiIKd-2S7wnU7ziQpb3sEfMMhQGKneMy1hAyNSsMUAEOwh58zjXQ-_Zicn5FX3BIPu5tIQ/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJbT8uK_jOUe1PBX7-nt8nAwcvxLjZkOks5sxezFgaJpZM4P2Fgo>.



———————————

John R. Peterson
Assoc. Professor of Physics and Astronomy
Department of Physics and Astronomy
Purdue University
525 Northwestern Ave.
West Lafayette, IN 47906
(765) 494-5193

**Comment by johnrpeterson** [comment]
To be clear.  This is what has been tested:

1)  The timing results so far are based on a realistic catalog with the right magnitude counts of stars & galaxies for a typical chip and a realistic typical background
2)  The timing results also were done on both NERSC haswell and knl nodes using various submission methods
3)  They were also done with the nodes *fully* loaded, which is very realistic and was apparently necessary for us to understand the efficiency of the multithreading

so this does test the actual throughput with realistic catalogs.  see what  i mean?  these tests so far were really run in a a realistic environment.

here’s what hasn’t been tested and should be, but is also unlikely to affect the estimate cost of the DC:

1)  the actual submission methodology of managing many jobs has to be tested and that is important, but that doesn’t affect timing
2)  a range of visits would test the different band timings, but we know that u band is a little faster and Y is a little slower, so the average of all bands will be within 10%
3)  a range of visits would test the extra time needed for moonlight.  however, we bounded this to probably be around 30% slower even when the moon is very close.  the reason this doesn’t matter that much anymore is that the quickbackground makes the moonlight and any background a minority of the runtime, so this doesn’t matter that much anymore.
4)  we would need to decide whether or not to include the 7-10 magnitude stars.  this isn’t really a timing question, and more of a science decision.  it will add some significant amount of time to the DC, but won’t really debilitate it like with v3.6.    there will be no ultralong simulation times (48hrs), but the brighter stars (say 7th) do take a lot of time.  there are some rather cool looking ghosts, but its a cost vs. benefit question.

john




On Oct 30, 2017, at 11:35 AM, Chris Walter <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi John,

Thanks. Yes, we know about this and Salman has reported on it to us.

We are trying to understand the relative scaling factors in the real environment we ran in before with a variety of realistic visits so we can tie the new numbers to the actual throughput. We will make sure any results are also reported so they can be incorporated.

**Comment by cwwalter** [comment]
Hi John,

Yes, exactly, the test is to get at what you list below.  We want to run with the representative set of visits from DC1 including moon, multiple bands etc with a multiple job submission.   We still need to decide what to do about the magnitude cut (asked above). 

The goal is to see what the time multiplication factor of running compared to what we had before was given the optimized threading and PhoSim optimization suggestions from the study by you and Salmon etc.  Since the  DC1 run also had the bugs related to the background level which probably resulted in a factor of about 5 in run time etc it isn't so simple to scale the run time using the calculated factors in the study.   This will measure it and should (I hope) give similar results to the numbers that Salman calculated.

**Comment by cwwalter** [comment]
Let's try to keep this issue focused on its topic and move further discussion on this topic if necessary to the other issue.

**Comment by johnrpeterson** [comment]
yes, i see what you mean, but the differences in moon, bands, etc. should all be at the 10-20% level variation, which is in the noise of the errors of the estimate.  still important to test, but it could be hard to get a more accurate estimate than the one we have already (short of actually rerunning DC1 entirely).

On Oct 30, 2017, at 2:45 PM, Chris Walter <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi John,

Yes, exactly, the test is to get at what you list below. We want to run with the representative set of visits from DC1 including moon, multiple bands etc with a multiple job submission. We still need to decide what to do about the magnitude cut (asked above).

The goal is to see what the time multiplication factor of running compared to what we had before was given the optimized threading and PhoSim optimization suggestions from the study by you and Salmon etc. Since the DC1 run also had the bugs related to the background level which probably resulted in a factor of about 5 in run time etc it isn't so simple to scale the run time using the calculated factors in the study. This will measure it and should (I hope) give similar results to the numbers that Salman calculated.

**Comment by salmanhabib** [comment]
Can someone tell me exactly what CCD effects DM can deal with right now, and what not? That will tell us what we don't have to worry about for the DC2 runs with either PhoSim or GalSim.

**Comment by cwwalter** [comment]
This is what we are working on.  It's not quite as clear cut as a simple answer..  please hold on a bit if possible.

**Comment by salmanhabib** [comment]
Sure, I can hold on or off, as desired ;-). A timeline would be good, though. Is the problem on the DM side or ours? If it's not on the DM side, then what is the hold-up?

**Comment by cwwalter** [comment]
Report on current understanding of DM handling of relevant effects we might want to turn on:

Brighter Fatter: The code to do the correction exists. However the code to produce the kernel has not yet been ported from HSC to LSST. This will not be ready by the end of the year.  We also are currently checking that simulated calibration products are realistic enough to be used.

Tree-rings: The is currently no code or attempt to handle this in either HST or LSST.  The effect is small in HST sensors so this has not been a priority.

Fringing: Sounds like it is not ready and there is no work on it.  There is something specific that may work on HSC.

Cosmic rays: Should work fine.  The version included works by looking for objects with features smaller than the PSF size and does not rely on differences between snaps.

Bleeding: should work with some tuning.

Defects/Hot pixels etc: Will work if we supply an input defect mask.

Cross-talk: Could be made to work; requires generalizing from the 4 amp HSC to 16 amp LSST sensors.

Debris / Dust:  Typically not a problem these days and it is suggested to omit it.

Saturation and non-linearity can be handled if DM knows what it is (they cannot measure it).

**Comment by johnrpeterson** [comment]
then the command file tentaively for both flats & regular images should be:

cleardefects
fringing 0
contaminationmode 0

backalpha 0.1
backbeta 4.0
backgamma 1000.0
backdelta 1.0
activebuffer 600

sourceperthread 100


i’m skeptical about some of this, but just taking what you are reporting at face value (i.e. yes there is dust & effects that are small should probably be on)



On Nov 3, 2017, at 1:04 PM, Chris Walter <notifications@github.com<mailto:notifications@github.com>> wrote:


Report on current understanding of DM handling of relevant effects we might want to turn on:

Brighter Fatter: The code to do the correction exists. However the code to produce the kernel has not yet been ported from HSC to LSST. This will not be ready by the end of the year. We also are currently checking that simulated calibration products are realistic enough to be used.

Tree-rings: The is currently no code or attempt to handle this in either HST or LSST. The effect is small in HST sensors so this has not been a priority.

Fringing: Sounds like it is not ready and there is no work on it. There is something specific that may work on HSC.

Cosmic rays: Should work fine. The version included works by looking for objects with features smaller than the PSF size and does not rely on differences between snaps.

Bleeding: should work with some tuning.

Defects/Hot pixels etc: Will work if we supply an input defect mask.

Cross-talk: Could be made to work; requires generalizing from the 4 amp HSC to 16 amp LSST sensors.

Debris / Dust: Typically not a problem these days and it is suggested to omit it.

Saturation and non-linearity can be handled if DM knows what it is (they cannot measure it).

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1Nyjw_3KoLwcIQeyvR2sUOWGDkXyhOKWNpK1afCo0tZo5qMVthMtR3BuCx7EvZHHd2bpIRnWRGqIfTVdCHoWhPi0fJwUFCU9GH2v3nW0ElycPhVwG-dH2tcsQ2NwYNkXrJFavwdj0nUxHSuNyQcDDNkD3KEPzZpF3d6kF8ibnMHYNFI2RheJH4klB_rwGv269X8I9U7F9X3ErYXo4F_zhu-DQAHbdL3Y1nyQrphvPygaWxsIfGem0BiUDGYR7Rrg1Y3tA7yCh7MofJ2rjiXcTij1EYhza2AdcMC4sEE32P8t-RcoyD7n4eNZHiQzxYcAcI9qUCmXMBUJMcAX4IF3wvfMsVTgZtSsxrnBhwb2I8uE/https%3A%2F%2Fgithub.com%2FLSSTDESC%2FDC2_Repo%2Fissues%2F4%23issuecomment-341766355>, or mute the thread<https://secure-web.cisco.com/1SboCgh4vQpD1pZDAY7mJIWEY-7BgHuDsiTrqfvqOHU1FRJY0uoer-c2h2TUF4z2nLNoDRKE2kQVN9kGt3kE1DH6hNsqEg4sIvQVhmQDVHmPFYCo4UGYl_2FisfHB5HjEyS7jrv1Hgr9_5QkKKREoB83ekyP77kvooy95SMamb7oSOlcfDKKf-528ZfKQay91T32vAwoON2NN-F3if_JkTqJm6GfzZzWyTiOofX1fZyjT7YjlOiRFr8Sc67FkyxJ-0GqDq34hKWae4QiQIJrqXNIA8x97_-9jm1xFz6oHbHuDz--Ql0PTljXylQ4dvZthr5m4cWzOBWFAW-9ZJqoY3xu4eqTumaqmZDllYe6MIqI/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJbT8uaJ-epHvoQZ5WKhhV10rPbgyljaks5sy0eigaJpZM4P2Fgo>.



———————————

John R. Peterson
Assoc. Professor of Physics and Astronomy
Department of Physics and Astronomy
Purdue University
525 Northwestern Ave.
West Lafayette, IN 47906
(765) 494-5193

**Comment by cwwalter** [comment]
For the record this is what was decided for DC2 after discussion with DM, WGs etc etc.

The list we decided to turn ON was:

BF, Tree rings, Cosmic rays, bleeding, X-talk,

Also on: hot columns/pixels. Note: we will need to supply and an input defect mask to DM.

Also on: non-linearity/saturation. Note: we will need to supply non-linearity info to DM ourselves. The cannot measure it.

Off:

Fringing, debris/dust.
