### ISSUE TITLE
DC2 dithering planning

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#5]
_From @humnaawan on June 11, 2017 21:0_

As the analysis for DC1 begins and efforts for DC2 ramp up, I wanted to report a few results. We tried finding the DC1 chip list using a different method as a cross-check; thanks to @danielsf. Comparing the numbers, we find that the other method produces 8434 more chips overall (~4.5% of the simulated DC1 science sensors) but misses some that are produced in the current list. Looking at the exact positions, the chips that are missing in one dataset and present in the other either lie at the boundary of the DC1 region or are (almost) outside the nominal circular FOV, e.g., see this short simulation for some examples:

![fid1447_both1024_subset](https://user-images.githubusercontent.com/12702187/27009030-d0970c72-4e37-11e7-9823-3ce9425d35b0.gif)

It isn’t clear if there’s a quick solution to the problem as the high HEALPix resolution to find the chips causes some pixels near the boundaries (FOV’s or DC1 region) to be deemed outside the visit, hence missing some chips (that are on the relevant raft and/or are in the region). While the impacts of these missing visits should be negligible for DC1**, we might need to think about a clever way to find all the chips that need to be simulated for DC2. Of course, a metric to estimate the expected number of chips (as was suggested in one of the SSim telecons) would help check whether the chip-finding technique is effective.

**If the missing chips were uniformly within the FOV region (which they are not and hence are not that critical), the 4.5% missing sensors would translate to a loss of about 0.02mag in differential depth.

_Copied from original issue: LSSTDESC/SSim_DC1#31_

**Comment by cwwalter** [comment]
Thanks @humnaawan!  It seems to me that, a certain point, doing the chip removal won't be really justified since the number of chips on the edges of the region will become fractionally non-important and won't really change the CPU/storage requirements substantially.

At 300sq we would have ~31 undithered visit locations.  Would there still be a substantial effect in this case?

**Comment by cwwalter** [comment]
@humnaawan and @egawiser Just following up/triaging some old issues: Would it be straightforward to make an estimate for the question I asked in the last comment?  Specifically, is it worth doing this sort of trimming for DC2 or is that already large enough that the extra sensor simulation is fractionally unimportant?

**Comment by cwwalter** [comment]
Wow. Attention @drphilmarshall. I used the tool here (written by Google):

https://github-issue-mover.appspot.com

To move/copy this entire issue to this repository from the DC1 repo to here.  Super handy!

The old one is still there and closed.

**Comment by cwwalter** [comment]
So @humnaawan putting this issue on your radar here in case you aren't subscribed to this repo.

**Comment by cwwalter** [comment]
I also just renamed this issue DC2 dithering planning.

**Comment by cwwalter** [comment]
Also, just noting as a reminder to us in a more permanent way our conversation on slack last week about understanding the rotational dither modulo the natural sky rotation.

**Comment by egawiser** [comment]
@cwwalter here is my back-of-envelope; @humnaawan please cross-check (and you might be asked to perform a more detailed simulation if it seems necessary).  In DC1, all 4 undithered "fields" are on the border of the region, so dithering created a decent fraction of extra chips that did not need to be simulated, and hence we saved significant CPU time by excluding them.  My back-of-envelope simply asks what fraction of the 31 undithered fields planned for DC2 would be on the borders.  Drawing that as a 5x6 "rectangle" of hexagons, there are 18 border fields out of 30.  Drawing it as close to a circle as I can, I get 16 border fields out of 30.  This implies that the fractional CPU savings in DC2 is ~16/30 what it was in DC1.  The truth appears to be less than that, because all 4 DC1 fields were "corners" whereas only ~6 of the border fields in DC2 are corners, so dithering keeps a larger fraction of chips within the desired region in most of the DC2 border fields.  Just estimating by eye, I'll bet that knocks ~0.5 down to ~0.3 of the fractional CPU savings.  That still doesn't sound negligible and is definitely more total CPU hours saved by not simulating "out of bounds" chips than was achieved in DC1.  We could of course adopt the simpler PhoSim implementation that John Peterson suggested of excluding out-of-bounds objects from all instance catalogs and setting minimum_sources_to_simulate=1, but then we wouldn't represent the impact of bright objects lying out of bounds.

**Comment by johnrpeterson** [comment]
We could of course adopt the simpler PhoSim implementation that John Peterson suggested of excluding out-of-bounds objects from all instance catalogs and setting minimum_sources_to_simulate=1, but then we wouldn't represent the impact of bright objects lying out of bounds.


Eric, if you want to be even more careful about this and want the impact of the bright objects.  You could do the following:

1) exclude all out-of-bounds objects from all instance catalogs but with an extra magnitude-dependent buffer
2) set the minimum sources to simulate to 1
3) then a conservative magnitude-dependent buffer is (0.2 arcseconds)*2.5^(17.-mag) that would capture all visible stray light/ghost/etc.

then only downside would be that you would then simulate some bright stars on some chips far from the survey region that would then have no faint stars/galaxies on them and you would throw those away.

john

**Comment by egawiser** [comment]
@johnrpeterson:  thanks for that nice clear suggestion.  Would it work to update to 2) set the minimum sources to simulate to ~100 ?   If I understand correctly, that should prevent simulating chips that happen to have a few bright stars but are out-of-bounds.

**Comment by johnrpeterson** [comment]
ah, yes.  very clever.  that should work.  i think even setting it to 2 or 3 might even work, because in practice we’d only be talking about the rather bright stars, but yeah there should be no reason that we’d want a chip with less than 100 sources.

john

On Oct 19, 2017, at 10:14 AM, Eric Gawiser <notifications@github.com<mailto:notifications@github.com>> wrote:


@johnrpeterson<https://secure-web.cisco.com/1wI2TjWR6RlIOf_3mHp_SR7sePwbmsi9Zf-jxqRHFUiVdCBdO6WRjPd5XwD47TQ8EZ_EmE_HnOQpXkJfeUD1FGYkoEbjGywVtFEOfw-3k9AehK6YRXFcTzk1ZnQkFz7ZQNgALKDHE4bBVX_1VIXDtUOlwX6-D3ow0O9yk5bWZAgyqVERqR30cXW4rL7HOIlmO7nBrd4BkPpT089c2jvHZqk4NSLUB3vAIE1OFgjNSwE9JSeA0VXBLaX5lp5BTANKYcVCrrwo7E-45lhNBDr1WpKLQqbqYHHgMF_tp4GKmfUjFsJakXrBURWQ_9b2VMYaGik0rqcPKTYZe12VqpLv_XZt3W86h6_vKOaCDgP4yYIY/https%3A%2F%2Fgithub.com%2Fjohnrpeterson>: thanks for that nice clear suggestion. Would it work to update to 2) set the minimum sources to simulate to ~100 ? If I understand correctly, that should prevent simulating chips that happen to have a few bright stars but are out-of-bounds.

**Comment by humnaawan** [comment]
@cwwalter I checked the locations of the missing chips in the main region (i.e., not the border of the region) and they always come out to be one or more of the ones outside the nominal circular FOV, i.e. the ones in red here:

![lsst fov - sometimes missing](https://user-images.githubusercontent.com/12702187/32745972-4dc93d22-c882-11e7-8732-a0a8d54480da.png)

Assuming that all DC2 chips will miss, on average, the same number of chips in the main region as in DC1, we'd be looking at ~3.7%  missing out of 1,384,920 (you can see the calculation at the end of the notebook [here](https://github.com/humnaawan/DC1-Regions/blob/master/notebooks/Missing%20DC1%20Chips%20-%20Border%20vs.%20Main.ipynb)). Whether or not this fraction will lead to problems is how much these chips matter, especially if they'd be vignetted (thoughts?). I think we'd circumvent this decision if we choose chips based on the PhoSim implementation as discussed above.

As for seeing the natural sky rotation in the GIFs, I added a few features that'll hopefully make things a little clearer. Here's an example:
![fid1447_2017-04-06data_nside1024 -- subset](https://user-images.githubusercontent.com/12702187/32749280-e2f883e4-c88c-11e7-8454-6be59be7f059.gif)

Also, as I noted in our slack conversation, we should not see rotational dithers in every visit if we look all the visits ordered by objHistID, as opposed to the GIF above where we have all visits to the field, ignoring visits to other fields during the time. Here's a GIF ordered by objHistID to illustrate the difference:

![hids_50-150index_2017-04-06data_nside1024 -- subset](https://user-images.githubusercontent.com/12702187/32749290-eabd7058-c88c-11e7-8fbb-8ea9e2e8008d.gif)

We can see quite a bit of natural rotation in the first GIF since we aren't looking at visits close in time, but the same is not true in the second case. Also, $\Delta$rotSkyPos and $\Delta$rotTelPos only change once there's a big jump in histIDs, during which a filter change is possible. Please let me know what you think.

Also, you can see more example of the GIFs [here](https://drive.google.com/file/d/151yl2z7qM123ZMiWAXWDDRPji0DySyZK/view?usp=sharing); please note that the folder is ~0.5GB in size.

**Comment by sethdigel** [comment]
> 3) then a conservative magnitude-dependent buffer is (0.2 arcseconds)*2.5^(17.-mag) that would capture all visible stray light/ghost/etc.

This magnitude-dependent buffer region that John mentioned is part of what phoSim does in constructing the trimcat files for individual CCDs from the instance catalog file (see [this line](https://bitbucket.org/phosim/phosim_release/src/bbeb01902667e724b90d1c1e31072eb9bf57295b/source/trim/trim.cpp?at=master&fileviewer=file-view-default#trim.cpp-171) in trim.cpp).  I'm not an expert, but I suspect that nothing more would need to be done regarding filtering the instance catalogs.  

From the discussion in this issue, I wasn't clear whether the idea would be to include bright stars only if they are off-CCD but within the buffer region, or whether they would be included within the CCD area as well.  In either case, we'd need to stop modifying the CatSim output to limit the instance catalog stars to be no brighter than magnitude 10.

**Comment by cwwalter** [comment]
> I'm not an expert, but I suspect that nothing more would need to be done regarding filtering the instance catalogs.

I recall there is also a setting you need to set to let PhoSim know not to simulate sensors with less than something like 200 sources. Otherwise those sources will wind up on other CCDs.  I think @johnrpeterson mentioned this in another issue.  

It would probably be good to test this feature/complete setup first to make sure it is all correctly setup and operating as expected.

**Comment by cwwalter** [comment]
@rmjarvis (I think) suggested we should do chip level dithers for the DDF.  Assuming that we kept the rotational dithers the same (one after each filter change) could this be accomplished by dividing the dithers already calculated by @humnaawan and @egawiser by a constant factor?

If no, I believe a new after burner column will need to be added to the minion database for the DDF proposal.

**Comment by humnaawan** [comment]
@cwwalter thinking of chip-level dithers as small dithers (i.e. on the scale of the chip size, as opposed to *large* dithers which are on the scale of the FOV; please correct me if I'm wrong), we can easily tweak the MAF Stackers to implement smaller dithers. Once we know what works, we can update the afterburner to write out columns for large dithers with WFD visits and small dithers for DDFs. I am a little unsure of what you mean by diviing dithers by a constant factor though.

Also, I am unsure of the timeline for Opsim v4 release, but @rhiannonlynne had mentioned to me that OpSim v3 code base is unsupposed right now. I wonder if we can still write an afterburner as before or if we will need to find a way to make MAF output the results of MAF Stackers into a database itself.

**Comment by cwwalter** [comment]
> thinking of chip-level dithers as small dithers (i.e. on the scale of the chip size, as opposed to large dithers which are on the scale of the FOV; please correct me if I'm wrong)

Right.

> I am a little unsure of what you mean by diviing dithers by a constant factor though.

I meant we have FOV scale dithers centered around the center of the pointing.  We will be putting in a reduced focal plane for the uDDF (a few rafts).  So I was wondering if we could take our hexagonal dither pattern and just reduce the distance for each shift by a constant factor so that the pattern was the same but that it was spread over a smaller area.  That way we wouldn't need to make new column.  Does that make sense?

**Comment by egawiser** [comment]
That would make perfect sense if the existing column was the dither vector.  But instead the existing columns are updated RA,DEC for the pointing after the random dither vector has been applied.  You could subtract to determine the dither vector, but since it's random, why not just pick a new random one with the desired expected amplitude and apply it to the central RA,DEC?

**Comment by drphilmarshall** [comment]
I think that's right: for chip-scale dithers, we'll need to re-do (or make separately) the dithered positions. BTW Robert Lupton commented on impacts of dithering on DM processing in #71 - bottom line is that we should be fine with the scheme discussed here. Remaining action required is to make sure the dithering plan is written down in the DC2 Plan.

**Comment by katrinheitmann** [comment]
@drphilmarshall @humnaawan @cwwalter Given that we have a new DC2 planning document, can we close this issue?

**Comment by katrinheitmann** [comment]
@drphilmarshall @humnaawan @cwwalter Hi all -- I am closing this issue for now. It dormant for 5 months and when I asked in March what the status is, nobody replied. I am pretty sure that this has been taken over by other issues. Feel free to reopen if you disagree! Thanks!
