### ISSUE TITLE
Choose WFD survey field center

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/DC2_Repo#54]
For DC1 this was done by @humnaawan, @egawiser and the LSS group.  As far as I know we do not yet have a DC2 field location.

A separate question is where if at all the DDF sits inside of the WFD survey.

**Comment by drphilmarshall** [comment]
I'd suggest we choose a DDF field position from the OpSim database, and
then select WFD visits around it. Why not the Twinkles field? (Extended
Chandra Deep Field South, RA: 03h 32m 30s Dec: -28d 06m 00s)

There are risks associated with DDF field placement:

* If the over-density of time-variable objects is a problem for the
analysis of the WFD visits, we need to be able to recover from that.

* If the time-variable objects or DDF/enhanced visit list are delayed, we
don't want to delay processing the main survey images.

I think we can mitigate both of these by putting the uDDF in the corner of
the main survey area rather than the center. Then, worst case scenario is
that we lose a corner of the main survey while a) the uDDF is simulated, or
b) ignored during main survey analysis.  Thoughts?

**Comment by fjaviersanchez** [comment]
@drphilmarshall I think that putting the uDDF is a good idea and it looks like that field is far from the galactic plane so for WL and LSS the stellar contamination and extinction should be low and I guess that for DC2 is fine to have those conditions. @slosar showed interest in having some sort of higher-than-average extinction to play with it while we were preparing DC1. Is this something that you are still interested in? (I think that if we want to study magnification maybe it is not a great idea to have high extinction/stellar contamination but maybe you want to make some tests in high-extinction conditions?)

**Comment by rbiswas4** [comment]
I second the suggestion of the TWINKLES field as a location for the uddf. 

I also agree that the over density of time dependent objects is a risk for the main survey, though I think this worry is perhaps overestimated (at least for SN). I think we need to be careful that this is not the case. 


I don't know the latest dither plan, but one of the advantages of having it at the center is that SN will not care, and others can implement their best dithers without it affecting us. Moving the uDDF to the corner affects us.

**Comment by drphilmarshall** [comment]
What if we put the uDDF region as close to a corner as we can without
losing any WFD image coverage? That shoudl still make the affected region
small compared to the main survey area, _if_ we need to excise it.

**Comment by rbiswas4** [comment]
That was the *only* worry, so if we ensure that this is true, I would not care about the uDDF being in the centre. If such a configuration exists (have not checked), we can all go home happy!

**Comment by katrinheitmann** [comment]
@drphilmarshall @cwwalter @rbiswas4 Since we have a new planning document for DC2 now, can we close this issue? Thanks!

**Comment by drphilmarshall** [comment]
I think so: the Run 2 main survey region field center will appear in the Run 2 specs note, ready to be applied in the extragalactic catalog when it is made.
