### ISSUE TITLE
Strongly Lensed Supernova+AGN, Host Galaxy, and Lens Galaxy Population Models

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2_Repo#58]
Subtask of #56. 

@dannygoldstein will provide @rbiswas4, @jbkalmbach, and @linan7788626 with OM10-style catalogs of lensed transient images, host galaxies, and lens galaxies. 

Tagged folks, could you please let me know exactly what columns you require.

**Comment by linan7788626** [comment]
@dannygoldstein Hi Danny, as you know, I will be tied to something else at the beginning of January, but I can work on our project during the holidays. Therefore, I am wondering whether you could please send me a toy catalog (10 systems are enough)? So that I can kick off the work on my side asap. The below information should be included in the toy catalog, thank you so much.

- the redshift of the sources (Supernovae, AGNs, Host Galaxies).
- the relevant positions of point sources (Supernovae, AGNs) to the center of lenses.
- the relevant positions of the host galaxies of point sources to the center of lenses.
- the light profile of the host galaxies, e.g., components, effective radii (in arcsec), axis ratio, position angle, apparent magnitudes...

**Comment by dannygoldstein** [comment]
Closing this as the lens galaxy population model is handled by the sprinkler, and the host galaxy population model is provided by the DC2 cosmology sims.
