### ISSUE TITLE
Time-evolving SEDs of strongly lensed transients 

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2_Repo#59]
Subtask of #56.

Given lensed image catalogs from @dannygoldstein, @rbiswas4 will generate time-evolving SEDs of lensed AGNs and supernovae (Type Ia + CCSNe) that can be called by PhoSim (and imSim?).

**Comment by rbiswas4** [comment]
@dannygoldstein It will be good to define what is meant by lensed image catalogs. There are two sets of questions in my mind:
## Questions on how the populations are defined
1. Should these lensed AGN and supernovae live in host galaxies of specific properties? 
2. Should these have anything in common with the AGNs and SNe that we are inserting. (ie we could imagine that some of them are being lensed), but given you have a large over-abundance, I am assuming this is not the case. ie. there will be lensed AGN objects that are entirely different from the AGNs that are being inserted in catsim.
3. If this is the case, what happens if there is a clash? ie. by chance a lensed AGN lands on a galaxy which originally had an AGN?

We have been using numbers in the planning document, but we need to use redshift distributions to discuss over-abundance. Having large numbers of dim objects at high redshift where there is large volume is different from having large numbers of objects at low redshifts.

## Questions on single objects
1. Example of the input you plan to provide for a lensed SN
2. Example of input you plan to provide for lensed AGN.

As discussed in our telecon, you could add them as examples in a github repository or on nersc.

**Comment by danielsf** [comment]
Have we already discussed the fact that implementing a full time-evolving SED model will mean writing all of these SEDs to disk somewhere so that PhoSim can read them back in?  I know we did something similar for the supernovae in Twinkles, but we did not do that for DC1.  I just want to make sure that the CI group is aware of whatever temporary storage challenges this may pose.

**Comment by rbiswas4** [comment]
@danielsf Good point. We can write the code, but scaling storage is important to consider too. I would just add that this is temporary (It needs to be on disk before PhoSim reads it, and need not be on disk after PhoSim is done). In principle, if we could also chunk them by time for SN, ie load only those SN which are within a time window of the visit being simulated. @jchiang87

**Comment by salmanhabib** [comment]
Any storage request estimates, @rbiswas4 ?

**Comment by dannygoldstein** [comment]
Hi @rbiswas4,

Answers to your questions:

> Should these lensed AGN and supernovae live in host galaxies of specific properties?

Yes. At least for SNe the rates as a function of  galaxy morphology were quantified by Li et al 2011, my plan was to use their results for this analysis. 

> Should these have anything in common with the AGNs and SNe that we are inserting. (ie we could imagine that some of them are being lensed), but given you have a large over-abundance, I am assuming this is not the case. ie. there will be lensed AGN objects that are entirely different from the AGNs that are being inserted in catsim.

No I think we should imagine these as being drawn from totally separate populations, at least for DC2. 

> If this is the case, what happens if there is a clash? ie. by chance a lensed AGN lands on a galaxy which originally had an AGN?

In this case I'd say we should just find another source galaxy for the AGN. 

For answers to the other two questions, see #68 .

Danny

**Comment by rbiswas4** [comment]
@salmanhabib 
@danielsf brought up this point about storage of transient seds and looking at this issue we realized that I had missed your question ... taking this to a separate issue to get storage estimates.

**Comment by jbkalmbach** [comment]
Closed with merging of LSSTDESC/sims_GCRCatSimInterface#22.
