### ISSUE TITLE
Sprinkler Examples

### ISSUE THREAD

**Issue by dannygoldstein** [LSSTDESC/DC2_Repo#68]
Subtask of #56. 

On a sprinkler-focused telecon Friday 12/15/17 I promised @rbiswas4, @jbkalmbach, and @linan7788626 small examples of glSN+host+lens catalogs that could be used for debugging purposes. 

I am diving into catalog production now and should have examples for you soon.

**Comment by dannygoldstein** [comment]
Hi all (esp. @linan7788626, @rbiswas4, @jbkalmbach), 

I'm happy to announce the release of the first set of DC2 sprinkler examples. Please use these to develop your downstream codes. 

What I have produced is a catalog of lensed images, lenses, and host galaxies of six strongly gravitationally lensed Type Ia supernovae (glSNe; 3 doubles, 3 quads). Each row in the catalog corresponds to one image of a glSN. I used the new protoDC2 cosmological simulation to supply host galaxies for these objects. protoDC2 uses a bulge+disk galaxy model via galacticus, and I have provided information about both components in the catalog. I used the Hsiao template to model the time-evolving SN Ia SED. The luminosities obey M_AB = -2.5 log L, where M_AB is the absolute magnitude in the AB system.

All coordinates are given with respect to the centroid of the lens (i.e., the lens is at x=0, y=0). 

Here are the columns in this test catalog and their definitions:

LSST_filters/diskLuminositiesStellar:LSST_g:rest - rest frame g-band luminosity of the disk component of the glSN host galaxy (no lensing)
LSST_filters/diskLuminositiesStellar:LSST_i:rest -  rest frame i-band luminosity of the disk component of the glSN host galaxy (no lensing)
LSST_filters/diskLuminositiesStellar:LSST_r:rest - rest frame r-band luminosity of the disk component of the glSN host galaxy (no lensing)
LSST_filters/diskLuminositiesStellar:LSST_u:rest - rest frame u-band luminosity of the disk component of the glSN host galaxy (no lensing)
LSST_filters/diskLuminositiesStellar:LSST_y:rest - rest frame y-band luminosity of the disk component of the glSN host galaxy (no lensing)
LSST_filters/diskLuminositiesStellar:LSST_z:rest - rest frame z-band luminosity of the disk component of the glSN host galaxy
LSST_filters/magnitude:LSST_g:observed - observed g-band AB mag of the glSN host galaxy (no lensing)
LSST_filters/magnitude:LSST_i:observed - observed i-band AB mag of the glSN host galaxy (no lensing)
LSST_filters/magnitude:LSST_r:observed - observed r-band AB mag of the glSN host galaxy (no lensing)
LSST_filters/magnitude:LSST_u:observed - observed u-band AB mag of the glSN host galaxy (no lensing)
LSST_filters/magnitude:LSST_y:observed - observed y-band AB mag of the glSN host galaxy (no lensing)
LSST_filters/magnitude:LSST_z:observed - observed z-band AB mag of the glSN host galaxy (no lensing)
LSST_filters/spheroidLuminositiesStellar:LSST_g:rest  - rest frame g-band luminosity of the bulge component of the glSN host galaxy (no lensing)
LSST_filters/spheroidLuminositiesStellar:LSST_i:rest - rest frame i-band luminosity of the bulge component of the glSN host galaxy (no lensing)
LSST_filters/spheroidLuminositiesStellar:LSST_r:rest - rest frame r-band luminosity of the bulge component of the glSN host galaxy (no lensing)
LSST_filters/spheroidLuminositiesStellar:LSST_u:rest - rest frame u-band luminosity of the bulge component of the glSN host galaxy (no lensing)
LSST_filters/spheroidLuminositiesStellar:LSST_y:rest - rest frame y-band luminosity of the bulge component of the glSN host galaxy (no lensing)
LSST_filters/spheroidLuminositiesStellar:LSST_z:rest - rest frame z-band luminosity of the bulge component of the glSN host galaxy (no lensing)
MB - rest frame B-band absolute magnitude of the SN Ia at peak (no lensing)
e - ellipticity of the SIE lens
galaxy_id - protoDC2 galaxy id of the host galaxy 
gamma - magnitude of the external shear 
imno - 0-based index of the image [0 = first image in this glSN system, 1 = second image in this glSN system, etc.]
morphology/diskEllipticity - ellipticity of the disk component of the host galaxy
morphology/diskHalfLightRadiusArcsec - effective radius of the disk component of the host galaxy, in Arcsec
morphology/diskSersicIndex - sersic index of the disk component of the host galaxy
morphology/inclination - inclination of the disk component of the host galaxy (not sure exactly how this is defined, perhaps @dkorytov or @yymao  can comment). 
morphology/spheroidEllipticity - ellipticity of the bulge component of the host galaxy
morphology/spheroidHalfLightRadiusArcsec - effective radius of the bulge component of the host galaxy, in Arcsec
morphology/spheroidSersicIndex - sersic index of the spheroid component of the host galaxy
mu - magnification of the image
position_angle - position angle of the host galaxy (degrees)
redshift_true - true redshift of the host galaxy (ignore) 
sigma - velocity dispersion of the SIE lens (km/s)
snx - x-coordinate of the supernova in the absence of lensing (arcsec)
sny - y-coordinate of the supernova in the absence of lensing (arcsec)
stellar_mass - stellar mass of the host galaxy (msun)
sysno - index of (host, lens, sn) system
t0 - time delay of this image (days)
theta_e - ellipticity angle of SIE lens (degrees)
theta_gamma - orientation angle of external shear (degrees)
x - x-coordinate of this lensed image (arcsec)
xhost - x-coordinate of the centroid of the host galaxy in the absence of lensing (arcsec)
y - y-coordinate of this lensed image (arcsec)
yhost - y-coordinate of the centroid of the host galaxy in the absence of lensing (arcsec)
zl - redshift of the lens
zs - redshift of the source 

The example catalog is available here as a pickled pandas dataframe:

http://w.astro.berkeley.edu/~dgold/static/glsn_protodc2.pkl

To read it into python do:

```python
import pickle
df = pickle.load(open('glsn_protodc2.pkl','rb'))
```

Please let me know if you have any questions. 

Thanks,
Danny

**Comment by dannygoldstein** [comment]
Also many thanks to @dkorytov and @yymao  for helping me do this over the holidays.

Danny

**Comment by rbiswas4** [comment]
Thanks @dannygoldstein . I have tried to do anything with it yet, but will try as soon as I am back.

**Comment by linan7788626** [comment]
Hi @dannygoldstein , thanks for the catalog, I played with it in past days, it looks good. One thing I want to mention is that the names of SEDs of the components of the hosts would be needed for the further work as well. On the other hand, could you please provide a catalog of the sources only? For example in current data, you have six systems, what I need are the properties of these six unlensed sources and the corresponding lenses (6 rows) instead of (17 rows), the shrinked catalog is like the list below. To match the future results from others, we would better set up an identical SystemID for each lensing system at the starting point (i.e., this catalog). Thanks a lot. By the way, my flight is tomorrow, but I will work on this next week. Please let me know if you have any questions. Cheers, Nan.

#### Sources (Host Galaxies)
- galaxy_id - protoDC2 galaxy id of the host galaxy
- LSST_filters/magnitude:LSST_g:observed - observed g-band AB mag of the bulge of the glSN host galaxy (in the absence of lensing)
- SED of the bulge of the glSN host galaxy
- LSST_filters/magnitude:LSST_g:observed - observed g-band AB mag of the disk of the glSN host galaxy (in the absence of lensing)
- SED of the disk of the glSN host galaxy
- morphology/diskEllipticity - ellipticity of the disk component of the host galaxy
- morphology/diskHalfLightRadiusArcsec - effective radius of the disk component of the host galaxy, in Arcsec
- morphology/diskSersicIndex - sersic index of the disk component of the host galaxy
- morphology/inclination - inclination of the disk component of the host galaxy (not sure exactly how this is defined, perhaps @dkorytov or @yymao can comment).
- morphology/spheroidEllipticity - ellipticity of the bulge component of the host galaxy
- morphology/spheroidHalfLightRadiusArcsec - effective radius of the bulge component of the host galaxy, in Arcsec
- morphology/spheroidSersicIndex - sersic index of the spheroid component of the host galaxy
- position_angle - position angle of the host galaxy (degrees)
- xhost - x-coordinate of the centroid of the host galaxy in the absence of lensing (arcsec)
- yhost - y-coordinate of the centroid of the host galaxy in the absence of lensing (arcsec)
- snx - x-coordinate of the supernova in the absence of lensing (arcsec)
- sny - y-coordinate of the supernova in the absence of lensing (arcsec)
- zs - redshift of the source

#### Lens galaxies
- sysno - index of (host, lens, sn) system
- sigma - velocity dispersion of the SIE lens (km/s)
- gamma - magnitude of the external shear
- theta_gamma - orientation angle of external shear (degrees)
- e - ellipticity of the SIE lens
- theta_e - ellipticity angle of SIE lens (degrees)
- zl - redshift of the lens

**Comment by dannygoldstein** [comment]
@linan7788626, here is the toy catalog with the sources only, containing all the columns you requested except the galaxy component SEDs:

http://w.astro.berkeley.edu/~dgold/static/system_catalog_protodc2.pkl

I am not sure exactly how to obtain the protoDC2 galaxy component SEDs.  I know the protoDC2 galaxies have been generated by Galacticus - perhaps @abensonca, @dkorytov, or @yymao could comment on how we could access the protoDC2 galaxy SEDs.

**Comment by yymao** [comment]
@dannygoldstein @linan7788626 
Here's an example of getting *all* SED info from `protoDC2`. You may want to further filter `sed_labels` to only get the relevant info you needed. 

```python
gc = GCRCatalogs.load_catalog('protoDC2')
sed_labels = [q for q in gc.list_all_quantities(True) if q.startswith('SEDs/')]
print('\n'.join(sorted(sed_labels)))
seds = gc.get_quantities(sed_labels) # loads all SEDs
```

**Comment by dannygoldstein** [comment]
@yymao 

In the SEDs quantities I see many items of the form

* SEDs/diskLuminositiesStellar:SED_1933_474:rest

I am interpreting this to mean: luminosity of the disk component of the galaxy between 1933 and 1933+474=2407 A in the galaxy's rest frame.

What are the units on these quantities? Are they specific or integrated luminosities?

Thanks,
Danny

**Comment by yymao** [comment]
@dannygoldstein Your interpretation is correct. The unit is 4.4659e13 W/Hz (AB luminosity).

I think they are integrated but I'm not sure on this one --- pinging @evevkovacs @abensonca @dkorytov

**Comment by abensonca** [comment]
As @yymao said, the luminosities are in AB luminosity units (what sometimes gets called "maggies"). The reason for this is that usually these luminosities are being computed for broad-band filters which we want to compare to data that is given in magnitudes. Outputting in maggies then means we can simply do M = -2.5 log L (where M is magnitude, and L is the output luminosity) - i.e the zero point is already taken care of.

Because of this, the luminosities are essentially integrated averages over the filter. Specifically, the luminosity is found by integrating the SED multiplied by the filter response curve over wavelength, and then this is zero-pointed by dividing by the integral of the AB reference luminosity multiplied by the filter response curve integrated over wavelength. 

In the case of these SED outputs the filter response curve is just a constant value between the two wavelengths, and zero outside (i.e. a top-hat filter).

**Comment by jbkalmbach** [comment]
Thanks @dannygoldstein. I'm back from holiday and looking through the catalog. One question. For a given image you mention the following:
* x - x-coordinate of this lensed image (arcsec)
* xhost - x-coordinate of the centroid of the host galaxy in the absence of lensing (arcsec)
* snx - x-coordinate of the supernova in the absence of lensing (arcsec)
 and the same for the y-coordinates. But will the offsets for the host galaxy and the supernova be the same in the lensed image? Are you saying that the geometry of the lensing doesn't affect the distance between xhost and snx and that the same `x` value can be added to `xhost` and `snx` to get the lensed image?

**Comment by rbiswas4** [comment]
@dannygoldstein Now that we are all back, can we (atleast you @jbkalmbach @danielsf to find a time more easily, but others can join if interested) briefly meet to discuss the sprinkler?  There are a few details we would like to understand : 
- What light curves would you like for the SN and AGN (AGN is a separate issue).
- How do we understand what properties should be used for the lensed SN (that ultimately determine light curves)

**Comment by linan7788626** [comment]
@dannygoldstein @yymao Thanks for the catalog and the example to extract SEDs. I was just back yesterday and am working on the project now. Cheers.

**Comment by jbkalmbach** [comment]
Ok, I think @dannygoldstein answered our questions in our conversation this morning and we can close this issue. What do you think @rbiswas4 ?

**Comment by jbkalmbach** [comment]
This was closed during our discussion last week.
