### ISSUE TITLE
Run 1.0 phosim results

### ISSUE THREAD

**Issue by katrinheitmann** [LSSTDESC/DC2_Repo#69]
In this issue we'll track the results that we get from PhoSim for Run 1.0, carried out on protoDC2. This can also be a stepping stone towards the more formal validation of the image files that we need to do. Tom is collecting the outputs here: /global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-2-r/output

**Comment by katrinheitmann** [comment]
@johnrpeterson Hi John, I looked at a random centroid_lsst_e_195452_f2_R43_S20_E000.txt file from the phosim and there are lots of nans in there: 
SourceID Photons AvgX AvgY
1125435218948 7769 3400.425151 3898.067061
1125434880004 62 3242.483871 3976.145161
1125434145796 0 -nan -nan
1125433789444 0 -nan -nan
838460647428 39615 3074.290471 4066.973167
1125436257284 0 -nan -nan

Is this expected? Where do they come from? Thanks a lot (I have obviously no good idea what should be in there and appreciate your help for me to get up to speed on better understanding the outputs!)

**Comment by katrinheitmann** [comment]
I have peeked at some of the output files from the phosim runs that Tom is producing and thought I would share the results here. From this very limited inspection, things look good -- no speckles or anything. I show below just a zoom in and a contour plot with the associated histogram. The experts should look more carefully though the run is obviously not complete yet.
![result2](https://user-images.githubusercontent.com/12860812/34321290-f4800638-e7d0-11e7-85d7-add7c71ee183.png)
![result1](https://user-images.githubusercontent.com/12860812/34321291-f495fc72-e7d0-11e7-8de0-2473e21e52e1.png)

**Comment by sethdigel** [comment]
@katrinheitmann The nans are listed for (faint) sources that generated no detected photons, so no centroid can be calculated.  The AvgX and AvgY are pixel coordinates in the output images.

**Comment by jchiang87** [comment]
Unfortunately, I have to bring not-so glad tidings about the current phosim runs.  Here is part of a field from the current runs in the r band, visit 889352:
![protodc2_889352_r_r22_s01](https://user-images.githubusercontent.com/1994473/34321629-90f8e4c0-e7c8-11e7-85d5-d93d4c855324.png)
and here is a visit from DC1, imsim dithered, r band, visit 40337:
![dc1_imsim_40337_r_r22_s01](https://user-images.githubusercontent.com/1994473/34321635-b39c1092-e7c8-11e7-8980-6c416e8105eb.png)

In contrast to the DC1 era image, in the protoDC2 image there are almost no galaxies evident. 
It seems that the reason for the apparent lack of extended objects is that the sersic major and minor axes for the protoDC2 instance catalogs are being written in radians instead of arcseconds (as required by phosim).

Here are histograms comparing the major axis ratios for DC1 and DC2 for representative samples:
![major_axis_dc1_vs_dc2](https://user-images.githubusercontent.com/1994473/34321715-ad95fb70-e7ca-11e7-8c25-90771f1ba2da.png)
Clearly multiplying the DC2 values by the factor to convert from radians to arcsec makes the distributions agree better.

For reference, here are comparisons of the axis ratios (major/minor) and r magnitudes:
![galaxy_axis_ratios](https://user-images.githubusercontent.com/1994473/34321671-e02e3abc-e7c9-11e7-957a-aab1622feb2f.png)
![r_mag_hists](https://user-images.githubusercontent.com/1994473/34321672-e46af44e-e7c9-11e7-9807-f0f5679099d3.png)
 
I think I know what changes to make to get the protoDC2 catalogs have the right galaxy major/minor axis units, but I need to check with Scott.  Until there is a fix, I guess we should stop the phosim production at NERSC.

**Comment by sethdigel** [comment]
Here's a plot showing the centers of the completed sensor visits, as of an hour or so ago.  It looks like the system for selecting the sensor visits to simulate for a given pointing is working.  I highlighted the positions of the sensor visits for obsHistID = 151687, which has the most (186) of any; I have not looked into why three sensor visits are missing from that pointing.

![show_coords](https://user-images.githubusercontent.com/6035835/34323109-5a2209d2-e7ef-11e7-9387-c06d73a5ba0f.png)

The completed sensor visits had 566 unique obsHistIDs, with an average of about 37 sensor visits per obsHistID.  You can see a gradient of density with RA.  I don't think that there's necessarily a problem, but I might look into it a bit more.  Each sensor visit covers a region about 0.22x0.22 deg.

**Comment by TomGlanzman** [comment]
@sethdigel The three missing sensors from visit 151687 (which is, in fact, the very first visit in the r-band) are simply queued and waiting to execute.   (And production was shut down a few hours ago.)

**Comment by jchiang87** [comment]
Here are couple of simulations of visit 450581 showing the middle of the central chip:
* on the left, using my kluge [here](https://github.com/LSSTDESC/gcr-catalogs/pull/56) to get seemingly reasonable galaxy major/minor axis values (and simulated via imsim), and
* on the right, the same field from the phosim protodc2 runs using the production instance catalog (i.e., without my kluge).
![image_comp_450581_r22_s11](https://user-images.githubusercontent.com/1994473/34323948-99501a40-e812-11e7-867c-07fcf119a261.png)

**Comment by sethdigel** [comment]
Here's a plot of median electrons/pixel vs. Moon altitude for the 20928 sensor visits in the DC-phoSim-2-r run.  These are all r-band observations.

![protodc2_bright](https://user-images.githubusercontent.com/6035835/34334362-bf63a308-e8fa-11e7-91a9-099fee294d93.png)

The vertical banding occurs because the sensor visits were accumulated over 566 visits, and so many sensor visits have the same metadata.  There's at least a suggestion of a dependence with moon altitude (which in the Twinkles era was the most important predictor of CPU time) and the typical value seems about right based on the estimates of @fjaviersanchez; this is probably the most important consideration right now.  I don't know what to expect but the scatter seems a bit large, and some sensor visits seem to have unusually low median electrons/pixel; this was also the case for DC2-phoSim-1. (The minimum is 30, which occurs for obsHistID 889352.)  I've posted a csv file with a wider variety of observing metadata for these sensor visits [here](http://www.slac.stanford.edu/~digel/lsst/DC2/protoDC2-phoSim-2-r.csv); the last column ('med') has the median electrons/pixel.

**Comment by cwwalter** [comment]
> I don't know what to expect but the scatter seems a bit large, and some sensor visits seem to have unusually low median electrons/pixel;

At some level, I am more surprised by the high median cases.  The low cases could in principle be caused by clouds, but what causes twice the expected sky level when the moon is 70 degrees below the horizon? Is the sky glow that much in the model?

Could we make the figure with more of a density plot like approach (or as a profile histogram) so we can better see the trend of the distribution?

**Comment by fjaviersanchez** [comment]
Thanks for the data @sethdigel. I am showing here some plots similar to what you did but color-coding with other quantities.

I thought that these high-background images might be due to twilight observations but it doesn't look like it:

![image](https://user-images.githubusercontent.com/13971732/34422070-25f411dc-ebe1-11e7-9276-645b2b50aa8c.png)

Then I checked if it was just close to the Moon:

![image](https://user-images.githubusercontent.com/13971732/34422125-7af20cd4-ebe1-11e7-94a0-7375f8555f4e.png)

Some of these are indeed due to being close to the Moon. And then I checked the Moon phase:

![image](https://user-images.githubusercontent.com/13971732/34422144-97c4cf7c-ebe1-11e7-8821-a33792053493.png)

And it looks like there's a correlation between the phase and the vertical stripe at ~0 deg.

**Comment by cwwalter** [comment]
Oh... didn't notice the link to the CSV file that Seth made. That's great thanks.  Javier, can you remake this with very small dots so we can see how they are distributed and if the ones on the edges are really outliers?

**Comment by fjaviersanchez** [comment]
![image](https://user-images.githubusercontent.com/13971732/34422895-8d67d8c6-ebe6-11e7-803e-dc18befcb686.png)
![image](https://user-images.githubusercontent.com/13971732/34422913-b1ff3468-ebe6-11e7-8e0d-cb62b494535e.png)
![image](https://user-images.githubusercontent.com/13971732/34422909-a8466c16-ebe6-11e7-89da-aec09e8468ff.png)
![image](https://user-images.githubusercontent.com/13971732/34422932-d1c5901c-ebe6-11e7-9811-dc2488e727bc.png)
![image](https://user-images.githubusercontent.com/13971732/34422937-dc4804e8-ebe6-11e7-8cce-0b6393d5c6b1.png)
![image](https://user-images.githubusercontent.com/13971732/34422943-e3405b88-ebe6-11e7-94d3-813759219451.png)

**Comment by sethdigel** [comment]
Beautiful plots, @fjaviersanchez.  I had looked at some of the potential correlations, but nothing really jumped out at me.  I guess that I see the point @cwwalter made about clouds = dark sky.  (I came from mm-wave astronomy where clouds = water vapor = bright sky.)  Maybe it would be interesting to look at the variations in median sky counts across the focal plane for a given visit, to see how systematic they are.  I don't think that the OpSim database has metadata about clouds, and I am not sure how much detail is available in the phoSim output about the clouds, including angular structure, for a given visit.

**Comment by RobertLuptonTheGood** [comment]
At good sites the clouds are darker than the sky in the optical (not true in Princeton or SLAC) even then the moon isn't up.  This should be a bigger effect in the red (e.g. i, z, y) than the blue (u, g).

**Comment by cwwalter** [comment]
John will need to confirm but I thought I was told (I can't remember by who) that in PhoSim the clouds extinct light but don't reflect moonlight etc.  But in any case we see cases in the plots with twice the expected level when the moon is at -70.  I think it would be good to just look at one of those cases in ds9 and see what is really going on.

**Comment by sethdigel** [comment]
At least part of the answer is vignetting.  Here's a visit (obsHistID = 1678834) with a large number of sensor visits simulated and one of the larger ranges of median electrons/pixel in the sensor visits, including 6 sensor visits with much lower medians than the rest of the distribution.

<img width="995" alt="assemble_1678834" src="https://user-images.githubusercontent.com/6035835/34427705-f8547c6c-ebf9-11e7-83eb-9106852c6e62.png">

(The gaps in the assembled image are presumably sensor visits that were in progress when the pipeline was stopped.). The scaling in the assembled image above is linear.  I'll update the csv file of metadata to include the CCD locations in the focal plane.

**Comment by sethdigel** [comment]
I've updated the [csv file](http://www.slac.stanford.edu/~digel/lsst/DC2/protoDC2-phoSim-2-r.csv) to add columns with the locations of the sensors in the focal plane.  The new columns are rx, ry, sx, and sy, extracted from the R##_S## parts of the file names.  rx is the x-coordinate of the raft, ry is the y-coordinate, and sx and sy are the coordinates of the CCDs in the rafts, in the mapping scheme defined in LCA-13381.  I also added a column 'radius' with the approximate angular distance of the CCD from the center of the focal plane, in units of CCD widths.  Roughly speaking, vignetting starts to look important for radius > 7.

Here's a quick plot showing the median electrons/pixel vs. moon altitude including only the sensor visits with radius <= 6.  The amount of scatter remaining in individual visits is difficult to judge in this plot, but it is certainly reduced.

![protodc2_bright](https://user-images.githubusercontent.com/6035835/34446315-e088da66-ec8e-11e7-9942-fbc376537697.png)

Considering only sensor visits with radius <=6, visit 1678834 (assembled image shown above) has the largest range of median electrons/pixel among its sensor visits.  For the 89 sensor visits, the full range is 251, the standard deviation is 58, and the average of the medians is 1699.   For other visits, the full range for radius <=6 sensor visits is typically ~100 or less.  So the sensor-to-sensor scatter in a given visit (presumably due to cloud variations) does not seem particularly extreme.  The correlation of the median electrons/pixel to the altitude of the Moon is not particularly striking but does seem to be positive.

**Comment by johnrpeterson** [comment]
good work, everyone, and happy new year.

for the background questions, the observations that are significantly higher and not related to the moon, off the top of my head, it probably is either:  1) twilight, 2) natural time variation (either random or solar activity-related).  

also there is some zodiacal variation but if you are looking at the same ra/dec roughly then it won't be that different, i think.  there are other things like absorption which as rather complicated to predict, as mentioned, but i don't think those would be a factor of 2.

**Comment by cwwalter** [comment]
> for the background questions, the observations that are significantly higher and not related to the moon, off the top of my head, it probably is either: 1) twilight, 2) natural time variation (either random or solar activity-related).

Thanks John.

I think it would be good to grab one of the x2 bright observations and take a look at them in DS9.  If it is just a few sensors then John's suggestion of twilight is a good one and the pattern might be apparent. Also, Javier maybe you could look at the local time/altitude?

John for " 2) natural time variation (either random or solar activity-related)." is there a plot in the PhoSim documentation where we could see the range expected (or could you tell us?)

**Comment by fjaviersanchez** [comment]
@cwwalter @johnrpeterson Happy new year! I checked the Sun's altitude and I would say that the images where the background is that high don't correspond to twilight (I'd say that the Sun is at ~-30 degrees) and there are pointings closer to twilight that don't show this behavior.

![image](https://user-images.githubusercontent.com/13971732/34509266-1f2d729c-f016-11e7-9fa8-3b5412ca0984.png)

@sethdigel For the median counts value that you show, are you using what the L2 pipeline gives you or are you calculating the raw median or a clipped median?

**Comment by sethdigel** [comment]
@fjaviersanchez Good question.  I calculated just the raw median.  From the distributions of the pixel counts of the (few) sensor visits I looked at individually, it seemed robust, in the sense of not being biased by stars and galaxies.  I could be wrong but I would not expect it to be a large effect.

Yes, none of the visits has Sun altitude >-18 deg, which is the definition of astronomical twilight.

**Comment by jchiang87** [comment]
Over at #65, Tom [comments](https://github.com/LSSTDESC/DC2_Repo/issues/65#issuecomment-358398794) that Run1.0b images are available. Here is a comparison of the Run1.0b image with the Run1.0a image for visit 151687 R:2,2 S:01:
![output_z4siqh](https://user-images.githubusercontent.com/1994473/35063268-74db266a-fb7b-11e7-83bb-87d1e1c7e229.gif)
The extension of the galaxies is apparent in the new image.  So, at least qualitatively, the galaxy major-minor axis fix seems to work.

**Comment by cwwalter** [comment]
Is it speckly? It's a bit hard to tell on that scale but looks like it might be.

**Comment by cwwalter** [comment]
It also look like the sky level might have changed (if the color scale is the same) is that expected?

**Comment by jchiang87** [comment]
I was wondering about the speckles too.  The file with the speckly object is `/global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-2-r/output/000000/lsst_e_151687_f2_R22_S01_E000.fits.gz`.  A cursory inspection seemed to indicate that the noise in the speckly parts was consistent with the sky noise, but someone should have a closer look.

I didn't try to use exactly the same stretch, so the automatic stretch that ds9 applies with zscale is being used and I think that depends on the image pixel values.  Again a cursory comparison of the sky levels leads me to believe they are consistent with each other and match the expected ~900 counts/pixel.

**Comment by sethdigel** [comment]
I looked at some of the new images last night.  My non-quantitative impression was that they looked fine - not speckled and they clearly had extended galaxies.  The speckling in the former run was not subtle.

**Comment by sethdigel** [comment]
Well, more quantitatively I'm afraid that it looks speckled.  Here is a comparison of profiles across the bright source (galaxy) in the same images.  In the new image, individual pixels in the wings of the galaxy have fluctuations of ~200 ADU on top of a background level of ~1000.

<img width="916" alt="profile_lsst_e_151687_f2_r22_s01_e000" src="https://user-images.githubusercontent.com/6035835/35065133-22d52a36-fb81-11e7-8a6b-1dd8e719b9c6.png">

**Comment by johnrpeterson** [comment]
is the center of the galaxy saturated?

**Comment by jchiang87** [comment]
It doesn't seem to be.  The peak counts for that object is ~8000 / pixel.

**Comment by sethdigel** [comment]
My impression is that the bright (even saturated) stars look fine, and more compact galaxies look at least close to fine.  I was thinking about scanning the trimcat files to find an even larger galaxy to see how it looked in the images.  That may or may not be useful, though.

**Comment by SimonKrughoff** [comment]
I agree that galaxy looks funny.  I can take a quick look.

**Comment by sethdigel** [comment]
Here's the trimcatalog entry for that galaxy.  It is definitely on the large side (sersic2d parameters are about 13" and 12").
`object 3333362765 0.776294878 0.618207323 15.397413492386292 galaxySED/Exp.50E09.1Z.spec.gz 0.0563707352 -4.51614396e-05 7.7834211e-06 0.000212330255 0 0 sersic2d 12.9612481 11.8222593 4869.20285 4 CCM 2.95326692 2.84221072 CCM 0.0773997701 3.1`

This is from /global/cscratch1/sd/descpho/Pipeline-tasks/DC2-phoSim-2-r/000000/work/trimcatalog_151687_R22_S01.pars

**Comment by SimonKrughoff** [comment]
OK, yes, it is definitely not Poisson.  I see individual pixel excursions of 700 on a background of ~1000.  That's a 22 sigma outlier and there are lots of examples around that galaxy.

**Comment by johnrpeterson** [comment]
is this v3.7.3 or later?

**Comment by katrinheitmann** [comment]
Tom should comment, but according to his notes on confluence it's 3.7.6.

**Comment by TomGlanzman** [comment]
Yes, @johnrpeterson this was run with v3.7.6 (cori-haswell-intel/phosim/v3.7.6).

**Comment by johnrpeterson** [comment]
could someone cut and paste the ~20 operational parameters in the catalog.  should be able to reproduce it with just those and the galaxy entry that seth put above.

**Comment by TomGlanzman** [comment]
@johnrpeterson here is the instanceCatalog for workflow stream 000000, sans the included star & galaxy files:

rightascension   0.5655039
declination   0.4238169
mjd   59783.2870136
altitude   49.5887656
azimuth   45.4182342
filter   2
rotskypos   222.2808973
camconfig   1
dist2moon   60.1932844
moonalt   -7.3351776
moondec   21.7013494
moonphase   24.2248480
moonra   59.3273733
nsnap   1
obshistid   151687
rottelpos   80.2567194
seed   151687
seeing   0.8579260
sunalt   -60.3770892
vistime   30.0000000
minsource   100
includeobj   star_cat_151687.txt.gz
includeobj   gal_cat_151687.txt.gz

====

And, for completeness, here is the command file:

# Enable centroid file
centroidfile 1

# Disable fringing
fringing 0

# Disable dirt
contaminationmode 0

# Quick background
backalpha 0.1
backbeta 4.0
backgamma 1000.0
backdelta 1.0
activebuffer 600

# Number of sources handled by a single thread
sourceperthread 100

**Comment by johnrpeterson** [comment]
hmm, having hard time reproducing it.  just ran just this galaxy + background and it looks smooth.
could one of you look at it and confirm that it is fundamentally different:

https://www.dropbox.com/s/opyi47l8vjmkrf6/lsst_e_151687_f2_R22_S01_E000_R000.fits.gz?dl=0

**Comment by sethdigel** [comment]
Yes, the noise looks much more consistent with Poisson fluctuations.  Here is the same profile that I plotted above, on the same scale.

<img width="919" alt="profile_lsst_e_151687_f2_r22_s01_e000_jp" src="https://user-images.githubusercontent.com/6035835/35076803-0a83183e-fbaf-11e7-971c-8c9de1b3d326.png">

**Comment by johnrpeterson** [comment]
Ok, hmm, then we can't reproduce it....Tom, can you make available the star and galaxy files?  Then we can run the exact same thing.

**Comment by cwwalter** [comment]
Hi John,

Wasn't one of the recent optimization problems something you found for some reason was only being triggered KNL and not on your laptop.  Glenn was looking into to understanding why that was. Could this be similar?

**Comment by TomGlanzman** [comment]
@johnrpeterson You may find the two included files (stars and galaxies) here:

NERSC:/global/cscratch1/sd/descpho/Pipeline-tasks/DC2-phoSim-2-r/000000/instCat

**Comment by sethdigel** [comment]
Tonight I played a little with making an algorithm that finds isolated pixels that stand way out from the level defined by their neighbors.  I haven't tuned it very much, but the results seem useful.  

The first image below shows the positions of the pixels that it flags in Tom's original run of this sensor visit (`/global/projecta/projectdirs/lsst/production/DC2/old.Dec2017/DC2-phoSim-2-r/output/000000/lsst_e_151687_f2_R22_S01_E000.fits.gz`).  The two clusters are artifacts around bright stars with bleed trails.
![nonpoi_lsst_e_151687_f2_r22_s01_e000_orig](https://user-images.githubusercontent.com/6035835/35086576-d81e231a-fbe1-11e7-9f52-1ff07794efed.png)
The image below shows the pixels it flags in the current version (`/global/projecta/projectdirs/lsst/production/DC2/DC2-phoSim-2-r/output/000000/lsst_e_151687_f2_R22_S01_E000.fits.gz`).   
![nonpoi_lsst_e_151687_f2_r22_s01_e000_new](https://user-images.githubusercontent.com/6035835/35086580-dae633f8-fbe1-11e7-9112-76411efb937a.png)
I'm not particularly worried about the few pixels that it flags in the original image, but in the new image it flags not only the region around the bright, large galaxy, but also some large regions not near any particularly bright source.  If you look at the FITS file in ds9, you can see them.  Here's a section near X = 3100 at the lower edge of the image.  The individual white pixels are up to ~1500 ADU, vs the background level of about 960.  I suppose that they could be resulting from bright, extended galaxies just outside the frame but they must be relatively far from the galaxies.

<img width="709" alt="image_inset_151687" src="https://user-images.githubusercontent.com/6035835/35086756-a1d28c5a-fbe2-11e7-886d-0cae5f667461.png">

**Comment by johnrpeterson** [comment]
ok, it must be a platform-specific bug like the other one.  fortunately, its not rare, so should be quick to track down.   glenn is working on it.  will update in a day or so.

**Comment by sethdigel** [comment]
I ran the same search for outstanding pixels on all 2012 of the Run 1.0b sensor visits that were available as of this morning (see Tom's posting [here](https://github.com/LSSTDESC/DC2_Repo/issues/65#issuecomment-358702015)).  By the definition of 'bad' that I provisionally adopted the median number of bad pixels in a sensor visit was 129.  The distribution is fairly steep, with a long tail.  The sensor visit that got us started looking at speckling yesterday is in fact the worst (12581).    For potential reference, here are the top five (all in /global/projecta/projectdirs/lsst/production/DC2/)
DC2-phoSim-2-r/output/000000/lsst_e_151687_f2_R13_S02_E000.fits.gz
DC2-phoSim-2-g/output/000004/lsst_e_158405_f1_R11_S01_E000.fits.gz
DC2-phoSim-2-r/output/000001/lsst_e_151723_f2_R10_S22_E000.fits.gz
DC2-phoSim-2-r/output/000000/lsst_e_151687_f2_R31_S11_E000.fits.gz
DC2-phoSim-2-i/output/000002/lsst_e_159248_f3_R33_S10_E000.fits.gz
These stand out from the others (and come from three different bands).  The first three have bright, large galaxies well contained in the sensor.  The last (with 4597) seems to have all of its speckling associated with something not in the field.  Here are the sensor image and the flagged pixels.

<img width="610" alt="image_lsst_e_159248_f4_r33_s10_e000" src="https://user-images.githubusercontent.com/6035835/35118066-84aa8796-fc45-11e7-9e48-f7fd2d20665a.png"><img width="594" alt="nonpoi_lsst_e_159248_f4_r33_s10_e000" src="https://user-images.githubusercontent.com/6035835/35118073-8a75aa0c-fc45-11e7-8435-ccb0192d4360.png">

A pixel x,y with p ADU is flagged 'bad' if its four nearest neighbors are all within 2*sqrt(p) of each other and p is more than 5\*sqrt(p) greater than the median of the neighbors.  I also added a requirement that the average of the pixels to the left and right of x,y not be more than sqrt(p) different from the average of the pixels above and below, and that p not be saturated at 100,000 (both to try to avoid flagging bleed trails).  I'm posting this in case these are useful for diagnosing the speckling.  A check like this might be a quick way to flag speckling, if the right field is selected.  I'll stop polluting the issue thread here.

**Comment by johnrpeterson** [comment]
try v3.7.7.   i'm not sure if this fixes it, but there was a known issue that could be related.

**Comment by johnrpeterson** [comment]
some progress by Glenn on this:

1) there is no speckling either on NERSC or other systems when that bright galaxy is simulated by itself
2) however, with other objects & background he has reproduced the speckling at NERSC
this is odd as the optimizer shouldn't care about the other objects to first order, but it should be quick to debug now that Glenn has reproduced it.

**Comment by sethdigel** [comment]
Tom is re-running visit 151687 with PhoSim 3.7.7 at NERSC.  They are still speckled.  (This is not a surprise - John indicated earlier today that Glenn has been able to reproduce the issue and they are working on it.)  Only a few of the sensor visits are complete as of yet, but here's a plot of the 'non-Poisson pixels' in one of them (from lsst_e_151687_f2_R43_S22_E000.fits.gz).

![nonpoi_lsst_e_151687_f2_r43_s22_e000](https://user-images.githubusercontent.com/6035835/35253373-e66b2be6-ff99-11e7-93c7-3b08760a8340.png)

**Comment by johnrpeterson** [comment]
PhoSim v3.7.8 is out and fixes the problem entirely!

There was a problem with the optimization of the galaxies when other saturated objects were in the field (i.e. stars).  This made it impossible to catch until we did full field simulations.

**Comment by SimonKrughoff** [comment]
The fix ticket is #105.  It would be good to post there when we can show that the problem is indeed fixed in the nominal pipelines.  Then we can close it.

**Comment by sethdigel** [comment]
Tom is re-running visit 151687 with PhoSim v3.7.8 at NERSC.  Several of the sensor visits have finished.  My first impression is that the speckling is fixed.  Here's a plot of the 'non-Poisson pixels' from the same sensor visit as I looked at in v3.7.7 yesterday.  The number of 'hot' pixels went from >1400 to 62, i.e., about the level the algorithm finds apparently at random or associated with bleed trails.  I'll take a look at some more of the images tonight and post something to issue #105 

![nonpoi_lsst_e_151687_f2_r43_s22_e000_v378](https://user-images.githubusercontent.com/6035835/35309785-f4f31ccc-0062-11e8-966a-c402f1019fd3.png)

**Comment by katrinheitmann** [comment]
Given that Run 1.0 has concluded, I am closing this issue.
