### ISSUE TITLE
WFD visits  and opsimdb

### ISSUE THREAD

**Issue by rbiswas4** [LSSTDESC/DC2_Repo#83]
I combined @humnaawan new dithers for WFD with depths and sky brightness calculations and saved the summary table in a hdf5 file: This is located on cori at `/global/cscratch1/sd/rbiswas/opsimdb/DC2/WFD/DC2_WFD.hdf`. 

To read it to get the summary columns, you can use if you use `pandas`:
```
df = pd.read_hdf('DC2_WFD.hdf')
```
@humnaawan @egawiser Is this useful for you to look at briefly, or do you need a sqlite file to begin? Even if this is not urgent,  I will create a sqlite file with this but wanted to discuss the column names, before doing that. This topic has been commented on by @egawiser and @drphilmarshall in #72 and I also had a short chat with @jchiang87 :
- The code that @jchiang87 pointed to in #72 https://github.com/LSSTDESC/sims_GCRCatSimInterface/blob/master/python/desc/sims/GCRCatSimInterface/InstanceCatalogWriter.py#L211
In my mind (and I chatted with @jchiang87 to get his opinion), an issue with this is that we are hardcoding the names of extra columns that do not exist in the official opsim databases. So, if we want to run our code, or have someone else run our code on an actual opsim, they will fail before we track every one of these and change them. From this point of view, it would be better to persist with OpSim official names to these columns, and replace the old columns by the ones we are using. This is also meaningful because people have thought about this and decided that things are  
- The problem with the above suggestion is provenance, and  understanding how these were created. My suggestion is that we give the database files names with a version number and whenever we make the opsim databases, we start by also having a description of the database (what were the input sources, changes, code ). If we want to obtain the ditheredRA from the official opsim (minion) and @humnaawan 's prescription, then we can do a join of the tables in these to obtain this information after the opsim columns have been rewritten in our version rather easily. So, we will not lose this information.

**Comment by egawiser** [comment]
@rbiswas4 thanks for the clear proposal and listing the pros & cons!  But I don't see why we should plan to run our codes on the current official opsim databases, which do not include dithers*, without adding columns.  One hopes that in the near future opsim will be upgraded to include dithering patterns, at which point we'll have "standard" column names to use for our purposes.   So the flip-side argument is that we want our codes to fail if someone mistakenly runs them on an official opsim database where nobody thought about what dithers to add.  

I'd be nervous about using opsim files where we overwrite undithered ra, dec, rotator positions with our desired dithered ones.  Plus, the way that we've been adding columns is exactly what you're supposed to do in MAF.  

*the exception is the hexdithra and hexdithdec columns; we could follow your proposal and overwrite those with our desired (non-hexagonal-lattice) dithers, but since there isn't one available for rotational dither position, I don't think this would help much.

**Comment by jchiang87** [comment]
I propose that we just add the columns using standard names as Phil proposed, i.e., descDitheredRA, etc. and be done with it. I think there are more critical things to hash out.

**Comment by rbiswas4** [comment]
I have put the first version of this as described on cori with one difference (I inserted a version number  in the database files to make sure we never refer to `minion_1016_desc_dithered.db` but a `minion_1016_desc_dithered_v1.db` : 

If you go to the directory `/global/cscratch1/sd/rbiswas/opsimdb/DC2/` I kept the files there. We can use a better location (there was a discussion that started about it). But I propose to having a directory here (or in the notes repository) to keep the visit_README.md and product versions DC2VisitsAndOpSimProducts.csv .

**Comment by rbiswas4** [comment]
I think this has served its purpose for now.
