### ISSUE TITLE
Truth tables: Contents and format

### ISSUE THREAD

**Issue by fjaviersanchez** [LSSTDESC/DC2_Repo#86]
With this issue I want to discuss what content and format we want for the DC2 truth tables.

I think that in the truth tables we should use one entry per galaxy (as pointed in #78) and use the instance catalogs positions and ellipticity + extra information from the extragalactic CS catalog.

Some discussion about the formatting is in #57 but, what will users want? A DB approach, pandas/dask? Other?

Basically, the problem is that we want something that is useful for the final user but fast and easy to use (remember that LSST is a lot of data).

Pinging some potential users/people that might have some insight: @kadrlica @damonge @slosar @timeifler @yymao @joezuntz @rmjarvis @rmandelb @drphilmarshall @cwwalter @jchiang87 @salmanhabib @SimonKrughoff @evevkovacs @dannygoldstein @chihway @erozo @anjavdl @reneehlozek @rbiswas4 @TallJimbo @danielsf @katrinheitmann  

Feel free to ping more people/apologies if I forgot anyone!

**Comment by yymao** [comment]
We faced the similar issue when we were dealing the extragalactic catalogs. Everyone has different opinions on what formats, naming schema, etc to use, and it is also difficult to predict what would be needed in the future. I think the lesson we've learned is that we should just do something sensible and not complicated (in terms of the underlying format), and then use the reader to provide a smooth and easy interface for the end users. When we change the underlying format in the future, we can just update the reader so that from the end users' point of view, the API does not change at all (or at least not change abruptly). The reader can also help integrating the instance catalogs and the extragalactic catalogs.

**Comment by cwwalter** [comment]
I think we should use a combination of database technology (we need to learn how to do it and Jim has pointed out it will be needed for the time domain cases in any case). And the pandas/dask approach. Pandas worked very well for DC1 and gave people an easy way to deal with and even download local files with a nice environment built into the python ecosystem that can also interface with astropy.

One important thing to remember is that the truth tables should be of the same format as the DM output catalog for things like matching being able to make comparison plots etc.

**Comment by cwwalter** [comment]
I am closing this issue so the more general discussion about formats can continue for both he DRP products and the truth tables together. Please continue this discussion in #117.
